// Visual effects and detail helpers shared by the scenes. Scenes import these; they do not edit this file.
// Everything here is procedural and cheap enough for a phone unless the note says desktop only.
//   rbox / tube / bundle     geometry for a Builder: rounded boxes, cables, cable bundles with sag
//   blinkers                 status LEDs that blink at their own rates (bloom picks them up)
//   lamps                    light fixtures: a bright face plus a soft halo sprite
//   plumes                   rising, spreading, fading particles: vapor off towers, warm air, exhaust
//   movers                   instanced assemblies driving or walking along polylines
//   floorMirror              a soft, dim reflection on a floor (desktop only: it renders the scene twice)
import { RoundedBoxGeometry } from 'three/addons/geometries/RoundedBoxGeometry.js';
import { Reflector } from 'three/addons/objects/Reflector.js';
import { THREE, Builder } from './kit.js';

// ---------- geometry for Builders ----------
const _rb = new Map();
// a box with rounded edges; radius as a fraction of the smallest side (default 8%)
export function rbox(B, w, h, d, mat, x, y, z, { r = 0.08, ry = 0 } = {}) {
  const k = `${w}|${h}|${d}|${r}`;
  if (!_rb.has(k)) _rb.set(k, new RoundedBoxGeometry(w, h, d, 2, Math.min(w, h, d) * r));
  return B.add(_rb.get(k), mat, x, y, z, 0, ry, 0);
}
// a cable through points (a smooth curve), radius r
export function tube(B, points, r, mat, { seg = 6, steps } = {}) {
  const curve = new THREE.CatmullRomCurve3(points.map(p => new THREE.Vector3(...p)));
  const n = steps ?? Math.max(8, Math.min(64, Math.round(curve.getLength() / r / 3)));
  return B.addM(new THREE.TubeGeometry(curve, n, r, seg, false), mat, new THREE.Matrix4());
}
// n cables from a to b, hanging with a sag, spread across a small bundle, cycling through mats
export function bundle(B, a, b, { n = 6, r = 0.01, spread = 0.04, sag = 0.1, mats, seed = 1, seg = 5 } = {}) {
  let s = seed; const rnd = () => (s = (s * 16807) % 2147483647) / 2147483647;
  const A = new THREE.Vector3(...a), Z = new THREE.Vector3(...b), dir = Z.clone().sub(A), len = dir.length();
  const side = new THREE.Vector3(-dir.z, 0, dir.x).normalize(); if (!isFinite(side.x) || side.lengthSq() < 1e-6) side.set(1, 0, 0);
  const up = new THREE.Vector3().crossVectors(side, dir).normalize();
  for (let i = 0; i < n; i++) {
    const ox = (rnd() - 0.5) * spread, oy = (rnd() - 0.5) * spread, dip = sag * (0.8 + rnd() * 0.4);
    const pts = [];
    for (let k = 0; k <= 4; k++) {
      const u = k / 4, p = A.clone().lerp(Z, u).addScaledVector(side, ox).addScaledVector(up, oy);
      p.y -= Math.sin(Math.PI * u) * dip * (len > 0 ? 1 : 0);
      pts.push(p.toArray());
    }
    tube(B, pts, r, mats[i % mats.length], { seg });
  }
  return B;
}

// ---------- status LEDs ----------
// items: { p: [x, y, z], color: '#5cf29a', rate: blinks per second (0 = steady), duty: 0-1 on share }
export function blinkers(items, { size = 0.01, k = 3.2 } = {}) {
  const geo = new THREE.BoxGeometry(size, size, size);
  const mat = new THREE.MeshBasicMaterial({ color: 0xffffff, toneMapped: false });
  const m = new THREE.InstancedMesh(geo, mat, Math.max(1, items.length));
  const c = new THREE.Color(), base = items.map(it => new THREE.Color(it.color || '#5cf29a').multiplyScalar(k));
  items.forEach((it, i) => { m.setMatrixAt(i, new THREE.Matrix4().makeTranslation(...it.p)); m.setColorAt(i, base[i]); });
  m.count = items.length;
  const phase = items.map((_, i) => (i * 0.7548) % 1);
  // Most frames flip only a few LEDs, so keep each one's last state, rewrite just the ones that flipped, and upload the
  // color buffer only when something did (every LED starts lit, as set above).
  const lit = new Uint8Array(items.length).fill(1);
  const update = t => {
    let changed = false;
    for (let i = 0; i < items.length; i++) {
      const it = items[i], rate = it.rate ?? 0.6;
      const on = rate === 0 || ((t * rate + phase[i]) % 1) < (it.duty ?? 0.7) ? 1 : 0;
      if (on === lit[i]) continue;
      lit[i] = on; changed = true;
      m.setColorAt(i, on ? base[i] : c.copy(base[i]).multiplyScalar(0.08));
    }
    if (changed && m.instanceColor) m.instanceColor.needsUpdate = true;
  };
  return { mesh: m, update };
}

// ---------- light fixtures ----------
const _haloTex = (() => {
  const cv = document.createElement('canvas'); cv.width = cv.height = 64; const g = cv.getContext('2d');
  const gr = g.createRadialGradient(32, 32, 0, 32, 32, 32);
  gr.addColorStop(0, 'rgba(255,255,255,1)'); gr.addColorStop(0.25, 'rgba(255,255,255,0.45)'); gr.addColorStop(1, 'rgba(255,255,255,0)');
  g.fillStyle = gr; g.fillRect(0, 0, 64, 64);
  const t = new THREE.CanvasTexture(cv); t.colorSpace = THREE.SRGBColorSpace; return t;
})();
// items: { p, w, d (the lit face, facing down), color }. Returns a Group: bright faces plus additive halos.
export function lamps(items, { color = '#fff1dc', k = 4, halo = 3, haloOpacity = 0.35 } = {}) {
  const g = new THREE.Group();
  const face = new THREE.InstancedMesh(new THREE.PlaneGeometry(1, 1), new THREE.MeshBasicMaterial({ color: new THREE.Color(color).multiplyScalar(k), toneMapped: false, side: THREE.DoubleSide }), items.length);
  const o = new THREE.Object3D();
  items.forEach((it, i) => { o.position.set(...it.p); o.rotation.set(-Math.PI / 2, 0, 0); o.scale.set(it.w, it.d ?? it.w, 1); o.updateMatrix(); face.setMatrixAt(i, o.matrix); });
  g.add(face);
  const pos = new Float32Array(items.length * 3); items.forEach((it, i) => pos.set(it.p, i * 3));
  const pg = new THREE.BufferGeometry(); pg.setAttribute('position', new THREE.BufferAttribute(pos, 3));
  const size = Math.max(...items.map(it => it.w)) * halo;
  g.add(new THREE.Points(pg, new THREE.PointsMaterial({ map: _haloTex, size, sizeAttenuation: true, color: new THREE.Color(color), transparent: true, opacity: haloOpacity, depthWrite: false, blending: THREE.AdditiveBlending })));
  return g;
}

// ---------- particles: vapor, warm air, exhaust ----------
// emitters: [{ p: [x, y, z], dir: [dx, dy, dz] }]. size in world units; life in seconds; rise in units/s.
export function plumes(emitters, { perEmitter = 24, size = 1, grow = 3, life = 6, rise = 1, drift = [0.3, 0, 0], spread = 0.3, color = '#e8eef6', opacity = 0.35, additive = false } = {}) {
  const n = emitters.length * perEmitter, pos = new Float32Array(n * 3), alpha = new Float32Array(n), sz = new Float32Array(n);
  const age = new Float32Array(n), seedX = new Float32Array(n), seedZ = new Float32Array(n);
  for (let i = 0; i < n; i++) { age[i] = (i % perEmitter) / perEmitter * life; seedX[i] = Math.sin(i * 12.9898) * 0.5; seedZ[i] = Math.sin(i * 78.233) * 0.5; }
  const geo = new THREE.BufferGeometry();
  geo.setAttribute('position', new THREE.BufferAttribute(pos, 3));
  geo.setAttribute('aAlpha', new THREE.BufferAttribute(alpha, 1));
  geo.setAttribute('aSize', new THREE.BufferAttribute(sz, 1));
  const mat = new THREE.ShaderMaterial({
    uniforms: { uColor: { value: new THREE.Color(color) }, uScale: { value: 1 } },
    vertexShader: `attribute float aAlpha; attribute float aSize; varying float vA;
      uniform float uScale;
      void main() { vA = aAlpha; vec4 mv = modelViewMatrix * vec4(position, 1.0); gl_Position = projectionMatrix * mv;
        gl_PointSize = aSize * uScale / max(0.001, -mv.z); }`,
    fragmentShader: `uniform vec3 uColor; varying float vA;
      void main() { vec2 d = gl_PointCoord - 0.5; float r = length(d) * 2.0; if (r > 1.0) discard;
        float a = vA * smoothstep(1.0, 0.0, r) * (0.75 + 0.25 * sin(r * 9.0));
        gl_FragColor = vec4(uColor, a); }`,
    transparent: true, depthWrite: false, blending: additive ? THREE.AdditiveBlending : THREE.NormalBlending,
  });
  const pts = new THREE.Points(geo, mat); pts.frustumCulled = false;
  // point size is in pixels per unit of depth: scale by the viewport so sizes are in world units
  pts.onBeforeRender = (renderer, scene, camera) => {
    const h = renderer.getDrawingBufferSize(new THREE.Vector2()).y;
    mat.uniforms.uScale.value = h / (2 * Math.tan(THREE.MathUtils.degToRad(camera.fov / 2)));
  };
  let last = 0;
  const update = t => {
    const dt = Math.min(0.1, Math.max(0, t - last)); last = t;
    for (let e = 0; e < emitters.length; e++) {
      const em = emitters[e], d = em.dir || [0, 1, 0];
      for (let j = 0; j < perEmitter; j++) {
        const i = e * perEmitter + j;
        age[i] += dt; if (age[i] > life) age[i] -= life;
        const u = age[i] / life, h = age[i] * rise;
        pos[i * 3] = em.p[0] + d[0] * h + drift[0] * age[i] + seedX[i] * spread * (1 + u * grow);
        pos[i * 3 + 1] = em.p[1] + d[1] * h + drift[1] * age[i];
        pos[i * 3 + 2] = em.p[2] + d[2] * h + drift[2] * age[i] + seedZ[i] * spread * (1 + u * grow);
        sz[i] = size * (1 + u * grow);
        alpha[i] = opacity * Math.min(1, u * 6) * (1 - u) * (1 - u);
      }
    }
    geo.attributes.position.needsUpdate = geo.attributes.aAlpha.needsUpdate = geo.attributes.aSize.needsUpdate = true;
  };
  update(0);
  return { points: pts, update };
}

// ---------- movers: vehicles and people along paths ----------
// build(B) draws one assembly at the origin facing +x. paths: arrays of [x, y, z]; each mover loops its path.
export function movers(build, paths, { speed = 5, perPath = 1 } = {}) {
  const B = new Builder(); build(B);
  const geos = B.geometries(), list = [];
  paths.forEach((pts, pi) => {
    const segs = []; let L = 0;
    for (let i = 1; i < pts.length; i++) { const a = new THREE.Vector3(...pts[i - 1]), b = new THREE.Vector3(...pts[i]); segs.push({ a, b, l0: L, len: a.distanceTo(b) }); L += a.distanceTo(b); }
    for (let k = 0; k < perPath; k++) list.push({ segs, L, off: (k / perPath + pi * 0.37) % 1 });
  });
  const g = new THREE.Group(), meshes = [];
  for (const [mat, geo] of geos) { const m = new THREE.InstancedMesh(geo, mat, list.length); m.castShadow = true; m.receiveShadow = true; m.userData.flowAuditIgnore = 'moving'; meshes.push(m); g.add(m); }   // traffic passes over a buried route; it is not one (tools/flow-audit.mjs)
  const o = new THREE.Object3D(), p = new THREE.Vector3();
  const update = t => {
    list.forEach((mv, i) => {
      let d = ((t * speed / mv.L + mv.off) % 1) * mv.L;
      const s = mv.segs.find(q => d <= q.l0 + q.len) || mv.segs[mv.segs.length - 1];
      p.lerpVectors(s.a, s.b, (d - s.l0) / s.len);
      o.position.copy(p); o.rotation.set(0, Math.atan2(-(s.b.z - s.a.z), s.b.x - s.a.x), 0); o.updateMatrix();
      meshes.forEach(m => m.setMatrixAt(i, o.matrix));
    });
    meshes.forEach(m => { m.instanceMatrix.needsUpdate = true; });
  };
  update(0);
  return { group: g, update };
}

// ---------- a soft floor reflection (desktop only) ----------
// A mirror rendered at reduced size, blurred a little, tinted and faded so the floor reads as polished concrete.
// Place it a hair above the floor; it draws with a polygon offset so it never fights the floor's depth.
export function floorMirror(w, d, { x = 0, y = 0, z = 0, res = 0.5, strength = 0.22, tint = '#9fb2cc', blur = 1.5 } = {}) {
  const px = Math.round(Math.min(2048, innerWidth * devicePixelRatio * res)), py = Math.round(Math.min(2048, innerHeight * devicePixelRatio * res));
  const m = new Reflector(new THREE.PlaneGeometry(w, d), {
    textureWidth: px, textureHeight: py, clipBias: 0.003, color: new THREE.Color(tint),
    shader: {
      name: 'SoftFloorShader',
      uniforms: { color: { value: null }, tDiffuse: { value: null }, textureMatrix: { value: null }, uStrength: { value: strength }, uBlur: { value: blur / px } },
      vertexShader: `uniform mat4 textureMatrix; varying vec4 vUv; varying vec3 vW;
        void main() { vUv = textureMatrix * vec4(position, 1.0); vW = (modelMatrix * vec4(position, 1.0)).xyz; gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0); }`,
      fragmentShader: `uniform vec3 color; uniform sampler2D tDiffuse; uniform float uStrength; uniform float uBlur; varying vec4 vUv;
        void main() {
          vec2 uv = vUv.xy / vUv.w; vec3 c = vec3(0.0);
          for (int i = -2; i <= 2; i++) for (int j = -2; j <= 2; j++) c += texture2D(tDiffuse, uv + vec2(float(i), float(j)) * uBlur).rgb;
          c /= 25.0;
          gl_FragColor = vec4(c * color, uStrength);
          #include <tonemapping_fragment>
          #include <colorspace_fragment>
        }`,
    },
  });
  m.material.transparent = true; m.material.depthWrite = false;
  m.material.polygonOffset = true; m.material.polygonOffsetFactor = -1; m.material.polygonOffsetUnits = -4;
  m.rotation.x = -Math.PI / 2; m.position.set(x, y, z); m.renderOrder = 1;
  m.userData.mirror = true;
  return m;
}
