// Sources for the "source popovers" on basis chips. SOURCES holds the reusable citations;
// PART_SOURCES and LEDGER_SOURCES point each card / ledger row at the citations behind it;
// EST_NOTES explains, in one sentence, how a handful of estimates were derived. Every URL
// here appears verbatim in research/*.md or in the footer of index.html — never invented.

export const SOURCES = {
  // grid, campus, transformers, generators
  'eia-td-losses': { title: 'How much electricity is lost in electricity transmission and distribution', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/tools/faqs/faq.php?id=105&t=5', published: '11/07/2023', dated: "11/07/2023 (page's own \"last updated\")", accessed: '09/27/2026', kind: 'primary' },
  'eia-co2-per-kwh': { title: 'How much carbon dioxide is produced per kilowatthour of U.S. electricity generation', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/tools/faqs/faq.php?id=74&t=11', published: '12/11/2024', dated: "12/11/2024 (page's own \"Last updated\")", accessed: '09/27/2026', kind: 'primary' },
  'epoch-stargate-abilene': { title: 'OpenAI Stargate: where the US sites stand', publisher: 'Epoch AI', url: 'https://epoch.ai/publications/openai-stargate-where-the-us-sites-stand', published: '04/17/2026', dated: "published 04/17/2026, updated 04/23/2026", accessed: '09/27/2026', kind: 'secondary' },
  'epoch-dc-abilene': { title: 'OpenAI Stargate Abilene, Frontier Data Centers (updated 09/24/2026)', publisher: 'Epoch AI', url: 'https://epoch.ai/data/ai-data-centers/directory/openai-stargate-abilene', published: '09/24/2026', dated: "updated 09/24/2026", accessed: '09/27/2026', kind: 'secondary' },
  'epoch-dc-colossus2': { title: 'xAI Colossus 2, Frontier Data Centers (updated 09/24/2026)', publisher: 'Epoch AI', url: 'https://epoch.ai/data/ai-data-centers/directory/colossus-2', published: '09/24/2026', dated: "updated 09/24/2026", accessed: '09/27/2026', kind: 'secondary' },
  'epoch-dc-fairwater-atl': { title: 'Microsoft Fairwater Atlanta, Frontier Data Centers (updated 09/24/2026)', publisher: 'Epoch AI', url: 'https://epoch.ai/data/ai-data-centers/directory/microsoft-fairwater-atlanta', published: '09/24/2026', dated: "updated 09/24/2026", accessed: '09/27/2026', kind: 'secondary' },
  'epoch-dc-fairwater-wi': { title: 'Microsoft Fairwater Wisconsin, Frontier Data Centers (updated 09/24/2026)', publisher: 'Epoch AI', url: 'https://epoch.ai/data/ai-data-centers/directory/microsoft-fairwater-wisconsin', published: '09/24/2026', dated: "updated 09/24/2026", accessed: '09/27/2026', kind: 'secondary' },
  'epoch-dc-hyperion': { title: 'Meta Hyperion, Frontier Data Centers', publisher: 'Epoch AI', url: 'https://epoch.ai/data/ai-data-centers/directory/meta-hyperion', published: '09/24/2026', dated: "updated 09/24/2026", accessed: '09/27/2026', kind: 'secondary' },
  'epoch-largest-dc': { title: 'Largest AI data centers by power capacity (updated 09/24/2026)', publisher: 'Epoch AI', url: 'https://epoch.ai/graphs/largest-ai-data-centers-by-power-capacity', published: '09/24/2026', dated: "updated 09/24/2026", accessed: '09/27/2026', kind: 'secondary' },
  'epoch-dc-new-carlisle': { title: "Anthropic-Amazon New Carlisle, Frontier Data Centers (updated 09/24/2026)", publisher: "Epoch AI", url: "https://epoch.ai/data/ai-data-centers/directory/anthropic-amazon-new-carlisle", published: '09/24/2026', dated: "updated 09/24/2026", accessed: '09/27/2026', kind: 'secondary' },
  'eia-state-indiana': { title: "Indiana Electricity Profile 2024", publisher: "U.S. Energy Information Administration", url: "https://www.eia.gov/electricity/state/indiana/", published: '11/10/2025', dated: "data for 2024; release date 11/10/2025", accessed: '09/27/2026', kind: 'primary' },
  'measuredai-new-carlisle': { title: "AWS New Carlisle Data Center Campus: Project Rainier — Where Anthropic Trains Claude", publisher: "Measured AI (Substack)", url: "https://measuredai.substack.com/p/aws-new-carlisle-data-center-campus", published: '06/16/2026', accessed: '09/27/2026', kind: 'secondary' },
  'compute-atlas-rainier': { title: "Amazon Project Rainier — Amazon Web Services data center in New Carlisle, IN", publisher: "Compute Atlas", url: "https://www.compute-atlas.com/facilities/amazon-project-rainier-new-carlisle-in", published: '08/16/2026', dated: "last updated 08/16/2026", accessed: '09/27/2026', kind: 'secondary' },
  'blackridge-rainier': { title: "AWS Project Rainier, Indiana: Latest Updates (2026)", publisher: "BlackRidge Research", url: "https://www.blackridgeresearch.com/project-profiles/aws-project-rainier-new-carlisle-indiana-usa-data-center-supercluster-cost-contractors-timeline-latest-updates", published: '04/15/2026', dated: "updated 04/15/2026", accessed: '09/27/2026', kind: 'secondary' },
  'epoch-dc-prometheus': { title: "Meta Prometheus", publisher: "Epoch AI", url: "https://epoch.ai/data/ai-data-centers/directory/meta-prometheus", published: '09/24/2026', dated: "updated 09/24/2026", accessed: '09/27/2026', kind: 'secondary' },
  'epoch-satellite-prometheus': { title: "Meta Prometheus — Frontier Data Centers Satellite Explorer", publisher: "Epoch AI", url: "https://epoch.ai/data/data-centers/satellite-explorer/MetaPrometheusNewAlbanyOhio", published: '09/24/2026', dated: "unknown for this specific view; the related directory page (same publisher) is updated 09/24/2026 and mentions imagery \"Latest: Aug. 31, 2026\"", accessed: '09/27/2026', kind: 'secondary' },
  'mlq-meta-gas-tents': { title: "Meta Deploys Tent-Based Data Centers in Ohio and Tennessee, Backed by 400MW of Off-Grid Gas Power", publisher: "MLQ.ai", url: "https://mlq.ai/news/meta-deploys-tent-based-data-centers-in-ohio-and-tennessee-backed-by-400mw-of-off-grid-gas-power/", published: '06/05/2026', accessed: '09/27/2026', kind: 'secondary' },
  'measuredai-prometheus-primer': { title: "Meta's Prometheus and Google's Central Ohio Cluster: An AI Data Center Primer", publisher: "Measured AI (Substack)", url: "https://measuredai.substack.com/p/meta-prometheus-google-ohio", published: '05/20/2026', accessed: '09/27/2026', kind: 'secondary' },
  'techcrunch-meta-tents': { title: "Meta steals a tactic from Tesla and builds data centers in tents", publisher: "TechCrunch", url: "https://techcrunch.com/2026/06/04/meta-steals-a-tactic-from-tesla-and-builds-data-centers-in-tents/", published: '06/04/2026', dated: "06/04/2026 12:33 PM PDT", accessed: '09/27/2026', kind: 'secondary' },
  'nvidia-sn5000-datasheet': { title: "Spectrum SN5000 Ethernet switch series data sheet", publisher: "NVIDIA", url: "https://nvdam.widen.net/s/mmvbnpk8qk/networking-ethernet-switches-sn5000-datasheet-us", published: '07/2025', dated: "datasheet footer reads \"4072600. JUL25\" / \"© 2025 NVIDIA Corporation\" -> revision dated 07/2025", accessed: '09/27/2026', kind: 'primary' },
  'nvidia-quantum-x800-switches': { title: "Quantum-X800 XDR InfiniBand switches (Q3400)", publisher: "NVIDIA", url: "https://networking-docs.nvidia.com/xdrswitcheshw/introduction", published: '08/21/2026', dated: "last updated 08/21/2026", accessed: '09/27/2026', kind: 'primary' },
  'nvidia-rubin-platform': { title: "Rubin platform: the chips of the next AI supercomputer", publisher: "NVIDIA", url: "https://nvidianews.nvidia.com/news/rubin-platform-ai-supercomputer", published: '01/05/2026', accessed: '09/27/2026', kind: 'primary', marketing: true },
  'nvidia-dpu-supernic': { title: "BlueField DPUs and ConnectX SuperNICs", publisher: "NVIDIA", url: "https://www.nvidia.com/en-us/networking/products/data-processing-unit/", published: '2026', dated: "unknown; only a generic \"© 2026 NVIDIA Corporation\" copyright, no page-specific date", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'nvidia-bluefield-datasheet': { title: "BlueField-3 DPU data sheet", publisher: "NVIDIA", url: "https://resources.nvidia.com/en-us-accelerated-networking-resource-library/datasheet-nvidia-bluefield", published: '04/07/2026', dated: "landing-page meta timestamp 04/07/2026 (og:article/date meta tag) -- not confirmed as the PDF's own revision date", accessed: '09/27/2026', kind: 'primary' },
  'nvidia-bluefield4-datasheet': { title: "BlueField-4 DPU data sheet", publisher: "NVIDIA", url: "https://resources.nvidia.com/en-us-accelerated-networking-resource-library/bluefield-4-dpu-datasheet", published: '10/28/2025', dated: "landing-page meta timestamp 10/28/2025 (og:article/date meta tag) -- not confirmed as the PDF's own revision date", accessed: '09/27/2026', kind: 'primary' },
  'cummins-qsk78': { title: "QSK78 diesel generator set", publisher: "Cummins", url: "https://www.cummins.com/en-na/generators/products/qsk78", dated: "unknown - could not access page content", unchecked: "blocked: Not retrievable by any method tried: WebFetch and direct curl both got HTTP 403 from a Cloudflare JS challenge (\"Cf-Mitigated: challenge\"); the r.jina.ai read-p", kind: 'primary', marketing: true },
  'cat-c175-16': { title: "C175-16 diesel generator set", publisher: "Caterpillar", url: "https://www.cat.com/en_US/products/new/power-systems/electric-power/diesel-generator-sets/1000028916.html", published: '03/14/2026', dated: "unknown specific revision date on the page; the Wayback snapshot used is timestamped 03/14/2026", accessed: '09/27/2026', via: 'Wayback Machine copy', kind: 'primary', marketing: true },
  'delta-ocp-800vdc': { title: "Delta demonstrates HVDC power, cooling and networking at the OCP Global Summit", publisher: "Delta Electronics", url: "https://www.deltapowersolutions.com/en/mcis/news-2025-delta-demonstrate-hvdc-power-cooling-networking-to-drive-ai-data-center-evolution-at-ocp-global-summit.php", published: '10/15/2025', accessed: '09/27/2026', kind: 'primary', marketing: true },
  'infineon-solaredge-sst': { title: "Infineon and SolarEdge partner on high-efficiency power for AI data centers", publisher: "Power Electronics News", url: "https://www.powerelectronicsnews.com/infineon-and-solaredge-partner-to-advance-high-efficiency-power-infrastructure-for-next-gen-ai-data-centers/", published: '11/05/2025', accessed: '09/27/2026', kind: 'secondary' },
  'liteon-gtc-2026': { title: "LITEON 800 VDC power rack and 110 kW power shelf, GTC 2026", publisher: "LITEON", url: "https://www.liteon.com/en/news/press-center/content/liteon-nvidia-gtc-2026", published: '03/17/2026', dated: "datePublished/dateModified 03/17/2026 per the page's own JSON-LD (+08:00)", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'skhynix-hbm4': { title: "SK hynix completes the first HBM4 development and readies mass production", publisher: "SK hynix", url: "https://news.skhynix.com/en/sk-hynix-completes-worlds-first-hbm4-development-and-readies-mass-production/", published: '09/12/2025', accessed: '09/27/2026', kind: 'primary', marketing: true },
  'micron-hbm4': { title: "HBM4", publisher: "Micron", url: "https://www.micron.com/products/memory/hbm/hbm4", dated: "unknown - no date visible on the page", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'samsung-hbm4': { title: "Samsung ships the first commercial HBM4", publisher: "Samsung Semiconductor", url: "https://semiconductor.samsung.com/news-events/news/samsung-ships-industry-first-commercial-hbm4-with-ultimate-performance-for-ai-computing/", dated: "unknown - not confirmed in this pass", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'innolight-1p6t': { title: "1.6T OSFP224 transceivers", publisher: "InnoLight", url: "https://www.innolight.com/data-center-networking/1.6t-osfp224", published: '2025', dated: "unknown specific date; footer copyright reads \"INNOLIGHT 2025\"", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'coherent-1p6t-dr8': { title: "1.6T DR8 OSFP transceiver", publisher: "Coherent", url: "https://www.coherent.com/networking/transceivers/datacom/FTCF2519E3PCA", published: '2026', dated: "unknown specific date; copyright year 2026", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'evapco-apex': { title: "APEX dry cooler", publisher: "EVAPCO", url: "https://www.evapco.com/apex", published: '2026', dated: "unknown; copyright year 2026", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'bac-data-centers': { title: "Data center cooling, including TrilliumSeries dry coolers", publisher: "Baltimore Aircoil Company", url: "https://baltimoreaircoil.com/data-centers", dated: "unknown - no date visible", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'schneider-uniflair': { title: "Uniflair cooling", publisher: "Schneider Electric", url: "https://www.se.com/us/en/work/products/master-ranges/uniflair/", dated: "unknown - no date visible", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'marvell-alaska-a-aec': { title: "Marvell extends connectivity leadership with the first 1.6T PAM4 DSP for active electrical cables", publisher: "Marvell, via PR Newswire", url: "https://www.prnewswire.com/news-releases/marvell-extends-connectivity-leadership-with-industrys-first-1-6t-pam4-dsp-for-active-electrical-cables-302184240.html", published: '06/27/2024', dated: "06/27/2024, 09:00 ET", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'credo-hiwire-800g-aec': { title: "Credo HiWire 800G AEC cables", publisher: "Open Compute Project marketplace", url: "https://www.opencompute.org/products/522/credos-hiwire-800g-aec-cables-straight", dated: "unknown - no listing date found; references a linked spec doc \"hiwire-specification-v1-0-ocp-submission\" with no date shown either", accessed: '09/27/2026', kind: 'secondary', marketing: true },
  'astera-taurus-scm': { title: "Taurus Ethernet smart cable modules", publisher: "Astera Labs", url: "https://www.asteralabs.com/products/taurus-ethernet-smart-cable-modules/", dated: "unknown - no date visible", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'marvell-ara-1p6t-portfolio': { title: "Marvell ushers in the 1.6T era with an expanded optical DSP portfolio", publisher: "Marvell", url: "https://investor.marvell.com/news-events/press-releases/detail/1013/marvell-ushers-in-the-1-6t-era-with-expanded-optical-dsp-platform-portfolio-redefining-ai-data-center-end-to-end-connectivity", published: '03/12/2026', accessed: '09/27/2026', kind: 'primary', marketing: true },
  'credo-bluebird-dsp': { title: "Bluebird 1.6T optical DSP", publisher: "Credo", url: "https://credosemi.com/products/optical-dsp/bluebird/", published: '2026', dated: "unknown - no date visible; copyright year 2026", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'marvell-colorz-800': { title: "Marvell launches the first 800G ZR/ZR+ modules for data center interconnects", publisher: "Marvell, via PR Newswire", url: "https://www.prnewswire.com/news-releases/marvell-launches-industrys-first-800g-zrzr-modules-for-data-center-interconnects-301907609.html", published: '08/23/2023', dated: "08/23/2023, 09:00 ET", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'ciena-wavelogic6-nano': { title: "WaveLogic 6 Nano: 800G pluggables and 1.6T Coherent-Lite", publisher: "Ciena", url: "https://www.ciena.com/insights/infobriefs/wavelogic-6-nano-1-6t-coherent-lite-pluggable-transceiver", published: '04/12/2026', dated: "unknown specific date; Wayback snapshot used is timestamped 04/12/2026", accessed: '09/27/2026', via: 'Wayback Machine copy', kind: 'primary', marketing: true },
  'broadcom-tomahawk6': { title: "Broadcom now shipping the first 102.4 Tb/s switch in production volume", publisher: "Broadcom", url: "https://www.broadcom.com/company/news/product-releases/64031", published: '03/12/2026', accessed: '09/27/2026', kind: 'primary', marketing: true },
  'marvell-teralynx10': { title: "Marvell Teralynx 10 51.2T Ethernet switch enters volume production for AI cloud deployments", publisher: "Marvell", url: "https://www.marvell.com/company/newsroom/marvell-teralynx-10-51-2t-ethernet-switch-enters-volume-production-for-global-ai-cloud-deployments.html", unchecked: "blocked: 403 Forbidden on WebFetch and direct curl with browser UA; Wayback Machine unreachable from this environment. Unverified.", kind: 'secondary', marketing: true },
  'compute-atlas-colossus': { title: 'xAI Colossus, Memphis, TN (checked 09/23/2026)', publisher: 'Compute Atlas', url: 'https://www.compute-atlas.com/facilities/xai-colossus-memphis-tn', published: '09/10/2026', accessed: '09/27/2026', kind: 'secondary' },
  'ieee-spectrum-hyperion': { title: '5GW Data Center Buildout Requires Novel Engineering', publisher: 'IEEE Spectrum', url: 'https://spectrum.ieee.org/5gw-data-center', published: '03/24/2026', accessed: '09/27/2026', kind: 'secondary' },
  'dcd-xai-colossus-memphis': { title: "Fury from campaigners as Elon Musk's xAI gets 150MW for Colossus supercomputer in Memphis", publisher: 'Data Center Dynamics', url: 'https://www.datacenterdynamics.com/en/news/xai-colossus-memphis-power-tva/', published: '11/08/2024', accessed: '09/27/2026', kind: 'secondary' },
  'semianalysis-xai-colossus2': { title: "xAI's Colossus 2 — First Gigawatt Datacenter", publisher: 'SemiAnalysis', url: 'https://newsletter.semianalysis.com/p/xais-colossus-2-first-gigawatt-datacenter', published: '09/16/2025', accessed: '09/27/2026', kind: 'secondary' },
  'pa-transformer-345kv': { title: '345 kV Power Transformer Projects', publisher: 'PA Transformer', url: 'https://www.patransformer.com/power-transformer-projects/power-transformer-345-kv/', accessed: '09/27/2026', kind: 'primary', marketing: true },
  'transformer-lead-times': { title: 'HV Transformer Lead Times 2026: EU vs US', publisher: 'GridReadiness', url: 'https://www.gridreadiness.com/blog/power-transformer-lead-times-ai-data-center-2026.html', published: '06/2026', accessed: '09/27/2026', kind: 'secondary', marketing: true },
  'doe-transformer-efficiency': { title: 'Energy Conservation Standards for Distribution Transformers, final rule', publisher: 'U.S. Department of Energy', url: 'https://www1.eere.energy.gov/buildings/appliance_standards/pdfs/dt_final_rule.pdf', published: '04/09/2013', accessed: '09/27/2026', kind: 'primary' },
  'mv-distribution-atk': { title: 'Medium-Voltage Distribution for Data Center Campuses in 2026', publisher: 'ATK Energy Group', url: 'https://atkenergygroup.com/blog/medium-voltage-distribution-data-center-campuses/', published: '05/15/2026', accessed: '09/27/2026', kind: 'secondary', marketing: true },
  'cummins-dqkan-genset': { title: 'DQKAN 2.5 MW generator data sheet', publisher: 'Cummins', url: 'https://www.globalpwr.com/wp-content/uploads/cut-sheets/gps-cummins-2500-kw-dqkan-data-sheet.pdf', published: '01/2023', accessed: '09/27/2026', kind: 'primary' },
  'nvidia-bess-blog': { title: 'Designing Production-Ready Battery Energy Storage Systems for AI Factories', publisher: 'NVIDIA', url: 'https://developer.nvidia.com/blog/designing-production-ready-battery-energy-storage-systems-for-ai-factories', published: '06/10/2026', accessed: '09/27/2026', kind: 'primary', marketing: true },
  'lv-distribution-busway': { title: 'LV Distribution: Busway, PDUs, RPPs & Rack Power', publisher: 'The Definitive Guide to AI Data Centers', url: 'https://aidatacenterguide.com/part-4-electrical-and-energy-infrastructure/4-6-lv-distribution-busway-pdus-rpps-and-rack-power', published: '09/2026', accessed: '09/27/2026', kind: 'secondary' },
  'zayo-route-diversity': { title: "Zayo's Unique Long-Haul Routes, setting the standard for network resilience", publisher: 'Zayo', url: 'https://www.zayo.com/info/zayos-unique-long-haul-routes-setting-the-standard-for-network-resilience/', published: '09/22/2025', accessed: '09/27/2026', kind: 'primary', marketing: true },

  // cooling and water
  'ashrae-liquid-cooling-classes': { title: "What You Need to Know About ASHRAE's Fifth Edition of Thermal Guidelines", publisher: 'Upsite Technologies', url: 'https://www.upsite.com/blog/what-you-need-to-know-about-ashraes-fifth-edition-of-thermal-guidelines/', published: '05/19/2021', accessed: '09/27/2026', kind: 'secondary', marketing: true },
  'introl-wue': { title: 'Water Usage Efficiency: AI Data Center Cooling Without Crisis', publisher: 'Introl', url: 'https://introl.com/blog/water-usage-efficiency-wue-ai-data-center-cooling-guide-2025', published: '02/12/2026', accessed: '09/27/2026', kind: 'secondary', marketing: true },
  'nrel-water-electricity': { title: 'A review of operational water consumption and withdrawal factors for electricity generating technologies', publisher: 'NREL', url: 'https://docs.nrel.gov/docs/fy11osti/50900.pdf', published: '03/2011', accessed: '09/27/2026', kind: 'primary' },
  'vertiv-coolchip-cdu': { title: 'Vertiv CoolChip CDU', publisher: 'Vertiv', url: 'https://www.vertiv.com/en-us/products-catalog/thermal-management/high-density-solutions/vertiv-coolchip-cdu/', accessed: '09/27/2026', kind: 'primary', marketing: true },
  'motivair-cdu-brochure': { title: 'CDU 2025 product brochure', publisher: 'Motivair (Schneider Electric)', url: 'https://www.motivaircorp.com/uploads/files/brochures/CDU%202025%20Motivair%20by%20SE_Updated_9_26_25.pdf', published: '09/26/2025', accessed: '09/27/2026', kind: 'primary', marketing: true },
  'fortum-finland-heat': { title: 'Fortum has started heat production at two large data centre sites in Finland', publisher: 'Fortum', url: 'https://www.fortum.com/en/media/2026/05/fortum-has-started-heat-production-two-large-data-centre-sites-finland', published: '05/06/2026', accessed: '09/27/2026', kind: 'primary' },
  'munters-odense': { title: 'Harnessing heat from Odense data center for reuse in district heating', publisher: 'Munters', url: 'https://www.munters.com/en-us/knowledge-bank/case-studies/casestudy-13666/', published: '04/18/2026', accessed: '09/27/2026', kind: 'primary', marketing: true },
  'stockholm-data-parks': { title: 'Stockholm Data Parks', publisher: 'Stockholm Exergi / City of Stockholm', url: 'https://stockholmdataparks.com/', accessed: '09/27/2026', kind: 'primary' },
  'microsoft-zero-water': { title: 'Sustainable by design: next-generation datacenters consume zero water for cooling', publisher: 'Microsoft', url: 'https://www.microsoft.com/en-us/microsoft-cloud/blog/2024/12/09/sustainable-by-design-next-generation-datacenters-consume-zero-water-for-cooling/', published: '12/09/2024', accessed: '09/27/2026', kind: 'primary', marketing: true },
  'alliance-chemical-gpu-thermal': { title: 'GPU Thermal Density & Coolant Flow Specs: B200, GB200, MI300', publisher: 'Alliance Chemical', url: 'https://alliancechemical.com/blogs/articles/gpu-thermal-density-b200-gb200-coolant-flow-specs', published: '04/27/2026', accessed: '09/27/2026', kind: 'secondary', marketing: true },

  // UPS, PUE
  'eaton-9395xr-ups': { title: '9395XR UPS', publisher: 'Eaton', url: 'https://www.eaton.com/us/en-us/catalog/backup-power-ups-surge-it-power-distribution/eaton-9395xr-ups.html', unchecked: "blocked: Every attempt (2x WebFetch, 2x direct curl) timed out or hung on TLS renegotiation; DNS/TCP connect succeeded so this looks like bot-shaping, not a dead domain.", kind: 'primary', marketing: true },
  'google-pue': { title: 'Efficiency — Google Data Centers', publisher: 'Google', url: 'https://datacenters.google/efficiency/', published: '2025', dated: "2025 (annual figure), updates through Q2 2026", accessed: '09/27/2026', kind: 'primary' },

  // GB200 / GB300 / 800 V DC rack platform
  'nvidia-gb200-nvl72': { title: 'GB200 NVL72', publisher: 'NVIDIA', url: 'https://www.nvidia.com/en-us/data-center/gb200-nvl72/', accessed: '09/27/2026', kind: 'primary', marketing: true },
  'nvidia-gb200-ocp': { title: 'NVIDIA Contributes GB200 NVL72 Designs to Open Compute Project', publisher: 'NVIDIA', url: 'https://developer.nvidia.com/blog/nvidia-contributes-nvidia-gb200-nvl72-designs-to-open-compute-project/', published: '10/15/2024', accessed: '09/27/2026', kind: 'primary', marketing: true },
  'nvidia-gb300-power': { title: 'How New GB300 NVL72 Features Provide Steady Power for AI', publisher: 'NVIDIA', url: 'https://developer.nvidia.com/blog/how-new-gb300-nvl72-features-provide-steady-power-for-ai/', published: '07/28/2025', accessed: '09/27/2026', kind: 'primary', marketing: true },
  'nvidia-gb300-nvl72': { title: 'GB300 NVL72', publisher: 'NVIDIA', url: 'https://www.nvidia.com/en-us/data-center/gb300-nvl72/', accessed: '09/27/2026', kind: 'primary', marketing: true },
  'nvidia-800v-hvdc': { title: 'NVIDIA 800 V HVDC Architecture Will Power the Next Generation of AI Factories', publisher: 'NVIDIA', url: 'https://developer.nvidia.com/blog/nvidia-800-v-hvdc-architecture-will-power-the-next-generation-of-ai-factories/', published: '05/20/2025', accessed: '09/27/2026', kind: 'primary', marketing: true },
  'hpe-gb200-quickspecs': { title: 'NVIDIA GB200 NVL72 by HPE, QuickSpecs', publisher: 'HPE', url: 'https://www.hpe.com/us/en/collaterals/collateral.a50009224enw.html', unchecked: "blocked: 2x WebFetch + 1x curl all failed (timeout/ECONNRESET) though DNS resolves fine. Search snippet suggests title matches sources.js, but unconfirmed by direct acce", kind: 'primary', marketing: true },
  'navitas-800vdc': { title: "Navitas Supports 800 VDC Power Architecture for NVIDIA's Next-Generation AI Factory Computing Platforms", publisher: 'Navitas Semiconductor', url: 'https://navitassemi.com/navitas-supports-800-vdc-power-architecture-for-nvidias-next-generation-ai-factory-computing-platforms/', published: '10/13/2025', accessed: '09/27/2026', kind: 'primary', marketing: true },
  'liteon-gb200-power-system': { title: 'NVIDIA GB200 Blackwell power system', publisher: 'LITE-ON', url: 'https://www.liteon.com/en/news/press-center/content/nvidia-gb200-blackwell-power-system', published: '06/03/2024', accessed: '09/27/2026', kind: 'primary', marketing: true },
  'nvidia-nvl72-reference-arch': { title: 'NVL72 AI Factory reference architecture, System Hardware & Components', publisher: 'NVIDIA', url: 'https://docs.nvidia.com/enterprise-reference-architectures/nvl72-ai-factory/latest/components.html', published: '09/15/2026', accessed: '09/27/2026', kind: 'primary' },
  'nvidia-dgx-gb200-hardware': { title: 'DGX GB Rack Scale Systems User Guide, Hardware', publisher: 'NVIDIA', url: 'https://docs.nvidia.com/dgx/dgxgb200-user-guide/hardware.html', published: '09/17/2026', accessed: '09/27/2026', kind: 'primary' },
  'servethehome-dgx-gb200': { title: 'This is the NVIDIA DGX GB200 NVL72', publisher: 'ServeTheHome', url: 'https://www.servethehome.com/this-is-the-nvidia-dgx-gb200-nvl72/', published: '03/19/2024', accessed: '09/27/2026', kind: 'secondary' },
  'naddod-gb200-interconnect': { title: 'NVIDIA GB200 Interconnect Architecture Analysis: NVLink, InfiniBand and Future Trends', publisher: 'NADDOD', url: 'https://www.naddod.com/blog/nvidia-gb200-interconnect-architecture-analysis-nvlink-infiniband-and-future-trends', published: '04/05/2024', dated: "04/05/2024 (published); modified 05/08/2026", accessed: '09/27/2026', kind: 'secondary', marketing: true },
  'amphenol-paladin-hd': { title: 'Paladin HD 224Gb/s Backplane Interconnect System', publisher: 'Amphenol', url: 'https://www.amphenol-cs.com/product-series/paladin-hd.html', unchecked: "blocked: 403 on WebFetch + 2x curl attempts. Search snippet shows matching title/URL indexed, but unconfirmed directly today.", kind: 'primary', marketing: true },
  'semianalysis-nvl72-optics': { title: "NVIDIA's Optical Boogeyman: NVL72, InfiniBand", publisher: 'SemiAnalysis', url: 'https://newsletter.semianalysis.com/p/nvidias-optical-boogeyman-nvl72-infiniband', published: '03/25/2024', accessed: '09/27/2026', kind: 'secondary' },
  'semianalysis-gb200-nvl72-specs': { title: 'NVIDIA GB200 NVL72 Specs, Pricing & AI Inference Benchmarks', publisher: 'SemiAnalysis / InferenceX', url: 'https://inferencex.semianalysis.com/chips/gb200-nvl72', accessed: '09/27/2026', kind: 'secondary' },

  // H100 / DGX H100
  'nvidia-h100-datasheet': { title: 'H100 Tensor Core GPU datasheet', publisher: 'NVIDIA', url: 'https://resources.nvidia.com/en-us-gpu-resources/h100-datasheet-24306', accessed: '09/27/2026', kind: 'primary', marketing: true },
  'nvidia-dgx-h100': { title: 'DGX H100 product page', publisher: 'NVIDIA', url: 'https://www.nvidia.com/en-eu/data-center/dgx-h100/', accessed: '09/27/2026', kind: 'primary', marketing: true },
  'fs-com-dgx-h100': { title: 'Introduction to NVIDIA DGX H100', publisher: 'FS.com', url: 'https://www.fs.com/blog/introduction-to-nvidia-dgx-h100-3856.html', unchecked: "blocked: SURPRISING: direct curl showed HTTP 202 with 'x-amzn-waf-action: challenge' (AWS WAF bot-challenge), not a real 404. Search found possibly-republished content a", kind: 'secondary', marketing: true },

  // networking, optics, fiber
  'nvidia-xdr-switch-specs': { title: 'Quantum-X800 XDR switch systems, specifications', publisher: 'NVIDIA', url: 'https://networking-docs.nvidia.com/xdrswitcheshw/specifications', published: '09/02/2026', accessed: '09/27/2026', kind: 'primary' },
  'nvidia-sn5000-specs': { title: 'SN5000 switch systems, specifications', publisher: 'NVIDIA', url: 'https://networking-docs.nvidia.com/sn5000hw/specifications', published: '2026', dated: "Last updated: June 15, 2026", accessed: '09/27/2026', kind: 'primary' },
  'nvidia-800g-dr8-datasheet': { title: '800Gb/s Twin-Port OSFP 2x400Gb/s Single-Mode DR8 datasheet', publisher: 'NVIDIA', url: 'https://docs.nvidia.com/nvidia-mms4x00-nm-800gbps-twin-port-osfp-2x400gb-s-single-mode-dr8-500m-12-07-2023.pdf', published: '2024', dated: "Rev 1.3, Mar 2024 (latest of 1.0 Dec 2022 - 1.3 Mar 2024)", accessed: '09/27/2026', kind: 'primary' },
  'nvidia-connectx8-datasheet': { title: 'ConnectX-8 SuperNIC datasheet', publisher: 'NVIDIA', url: 'https://resources.nvidia.com/en-us-accelerated-networking-resource-library/connectx-datasheet-c', accessed: '09/27/2026', kind: 'primary' },
  'nvidia-spectrum-x-cpo': { title: 'NVIDIA Spectrum-X co-packaged optics networking switches for AI factories', publisher: 'NVIDIA', url: 'https://nvidianews.nvidia.com/news/nvidia-spectrum-x-co-packaged-optics-networking-switches-ai-factories', published: '2025', dated: "March 18, 2025", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'broadcom-davisson-cpo': { title: 'Broadcom Davisson co-packaged optics announcement', publisher: 'Broadcom', url: 'https://www.broadcom.com/company/news/product-releases/63626', published: '2025', dated: "October 8, 2025 (via GlobeNewswire mirror)", accessed: '09/27/2026', via: 'indirect copy (see research notes)', kind: 'primary', marketing: true },
  'nvidia-spectrum-xgs': { title: 'NVIDIA Introduces Spectrum-XGS Ethernet to Connect Distributed Data Centers', publisher: 'NVIDIA', url: 'https://nvidianews.nvidia.com/news/nvidia-introduces-spectrum-xgs-ethernet-to-connect-distributed-data-centers-into-giga-scale-ai-super-factories', published: '2025', dated: "August 22, 2025", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'microsoft-ai-wan': { title: 'From Wisconsin to Atlanta: Microsoft connects datacenters to build its first AI superfactory', publisher: 'Microsoft', url: 'https://news.microsoft.com/source/features/ai/from-wisconsin-to-atlanta-microsoft-connects-datacenters-to-build-its-first-ai-superfactory/', published: '2025', dated: "November 12, 2025", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'datacenterfrontier-fairwater': { title: "Microsoft's Fairwater Atlanta and the Rise of the Distributed AI Supercomputer", publisher: 'Data Center Frontier', url: 'https://www.datacenterfrontier.com/machine-learning/article/55330039/microsofts-fairwater-atlanta-and-the-rise-of-the-distributed-ai-supercomputer', published: '2025', dated: "Nov. 21, 2025", accessed: '09/27/2026', kind: 'secondary' },
  'google-cloud-networking-ai': { title: 'Data center and global networks built for the AI era', publisher: 'Google Cloud', url: 'https://cloud.google.com/blog/products/networking/data-center-and-global-networks-built-for-ai-era', published: '2026', dated: "May 26, 2026", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'deepmind-decoupled-diloco': { title: 'Decoupled DiLoCo', publisher: 'Google DeepMind', url: 'https://deepmind.google/blog/decoupled-diloco/', published: '2026', dated: "April 23, 2026", accessed: '09/27/2026', kind: 'primary' },
  'ciena-wavelogic6': { title: 'Ciena Unveils WaveLogic 6', publisher: 'Ciena', url: 'https://www.ciena.com/about/newsroom/press-releases/ciena-unveils-wavelogic-6', published: '2023', dated: "February 21, 2023 (Hanover, Md. dateline)", accessed: '09/27/2026', via: 'Wayback Machine copy', kind: 'primary', marketing: true },
  'corning-edge8': { title: 'EDGE8 Housings', publisher: 'Corning', url: 'https://ecatalog.corning.com/optical-communications/US/en/Fiber-Optic-Hardware/Housings/EDGE8%C2%AE-Housings/p/EDGE8-01U-SP', dated: "unknown (broken copyright template; future-dated timestamp artifact seen)", accessed: '09/27/2026', kind: 'primary' },
  'coherent-full-cband-pols': { title: 'ECOC: Coherent Extends Pluggable Line System Across Full C-Band', publisher: 'Converge Digest', url: 'https://convergedigest.com/coherent-full-c-band-pols-25-6tbps-ai-dci/', published: '2026', dated: "September 20, 2026", accessed: '09/27/2026', kind: 'secondary' },
  'cisco-8800-routers': { title: '8800 Series Modular Routers data sheet', publisher: 'Cisco', url: 'https://www.cisco.com/c/en/us/products/collateral/routers/8000-series-routers/8800-series-modular-routers-ds.html', published: '2026', dated: "Updated June 22, 2026", accessed: '09/27/2026', kind: 'primary' },
  'microsoft-hollow-core-fiber': { title: 'Microsoft Scales Up Hollow Core Fiber Production', publisher: 'Fiber Broadband Association', url: 'https://fiberbroadband.org/2026/04/02/microsoft-scales-up-hollow-core-fiber-production/', published: '2026', dated: "April 2, 2026", accessed: '09/27/2026', kind: 'secondary' },
  'prysmian-flexribbon': { title: 'FlexRibbon whitepaper', publisher: 'Prysmian', url: 'https://www.prysmian.com/sites/default/files/business_markets/markets/downloads/datasheets/FlexRibbon-Whitepaper.pdf', published: '2019', dated: "PDF created March 27, 2019", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'google-ironwood-tpu': { title: 'Ironwood: the first Google TPU for the age of inference', publisher: 'Google Cloud', url: 'https://blog.google/products/google-cloud/ironwood-google-tpu-things-to-know/', published: '2025', dated: "Nov 25, 2025", accessed: '09/27/2026', kind: 'primary', marketing: true },

  // board, chip, power delivery
  'semianalysis-blackwell-power-delivery': { title: 'Energizing AI: Power Delivery Competition Heats Up', publisher: 'SemiAnalysis', url: 'https://newsletter.semianalysis.com/p/energizing-ai-power-delivery-competition', published: '2023', dated: "Aug 01, 2023", accessed: '09/27/2026', kind: 'secondary' },
  'arxiv-gpu-power-visibility': { title: 'Methodology for Fine-Grain GPU Power Visibility and Insights', publisher: 'arXiv', url: 'https://arxiv.org/html/2412.12426v1', published: '2024', dated: "17 Dec 2024 (v1)", accessed: '09/27/2026', kind: 'primary' },
  'nvidia-blackwell-ultra-blog': { title: 'Inside NVIDIA Blackwell Ultra: The Chip Powering the AI Factory Era', publisher: 'NVIDIA', url: 'https://developer.nvidia.com/blog/inside-nvidia-blackwell-ultra-the-chip-powering-the-ai-factory-era', published: '2025', dated: "Aug 22, 2025", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'wccftech-nv-hbi': { title: 'NVIDIA Deep-Dives Into Blackwell Infrastructure: NV-HBI Used to Fuse Two AI GPUs Together', publisher: 'WCCFTech', url: 'https://wccftech.com/nvidia-blackwell-ai-deep-dive-nv-hbi-fuse-two-ai-gpus-together-5th-gen-tensor-cores-5th-gen-nvlink-spectrum-x/', published: '2024', dated: "Aug 27, 2024", accessed: '09/27/2026', kind: 'secondary' },
  'micron-hbm3e-brief': { title: 'HBM3E product brief', publisher: 'Micron', url: 'https://assets.micron.com/adobe/assets/urn:aaid:aem:b710d8f2-7f66-44c1-a234-456e2b986347/original/as/hbm3e-product-brief.pdf', published: '10/2023', dated: "footer reads \"Rev. C 10/2023\"", accessed: '09/27/2026', via: 'Wayback Machine copy (the live URL is WAF-blocked)', kind: 'primary', marketing: true },

  // tokens, training, carbon, models
  'samsi-words-to-watts': { title: 'From Words to Watts: Benchmarking the Energy Costs of Large Language Model Inference', publisher: 'Samsi et al., arXiv', url: 'https://arxiv.org/pdf/2310.03003', published: '2023', dated: "4 Oct 2023 (v1)", accessed: '09/27/2026', kind: 'primary' },
  'semianalysis-inferencemax': { title: 'InferenceMAX: Open Source Inference Benchmarking', publisher: 'SemiAnalysis', url: 'https://newsletter.semianalysis.com/p/inferencemax-open-source-inference', published: '2025', dated: "Oct 09, 2025", accessed: '09/27/2026', kind: 'secondary' },
  'google-inference-impact': { title: 'Measuring the environmental impact of AI inference', publisher: 'Google Cloud', url: 'https://cloud.google.com/blog/products/infrastructure/measuring-the-environmental-impact-of-ai-inference/', published: '2025', dated: "August 21, 2025", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'google-inference-impact-paper': { title: 'Measuring the environmental impact of delivering AI at Google scale', publisher: 'Google, arXiv', url: 'https://arxiv.org/abs/2508.15734', published: '2025', dated: "Submitted 21 Aug 2025", accessed: '09/27/2026', kind: 'primary' },
  'meta-llama31-model-card': { title: 'Llama 3.1 model card', publisher: 'Meta', url: 'https://github.com/meta-llama/llama-models/blob/main/models/llama3_1/MODEL_CARD.md', published: '2024', dated: "Model Release Date: July 23, 2024", accessed: '09/27/2026', kind: 'primary' },
  'meta-llama3-herd-parallelism': { title: 'The Llama 3 Herd of Models', publisher: 'Meta AI, arXiv', url: 'https://arxiv.org/pdf/2407.21783', published: '2024', dated: "July 23, 2024 (paper date); v3 23 Nov 2024 (current arXiv version)", accessed: '09/27/2026', kind: 'primary' },
  'deepseek-v3-technical-report': { title: 'DeepSeek-V3 Technical Report', publisher: 'DeepSeek-AI, arXiv', url: 'https://arxiv.org/pdf/2412.19437', published: '2024', dated: "Submitted 27 Dec 2024", accessed: '09/27/2026', kind: 'primary' },
  'nvidia-gb200-dynamo-moe': { title: 'How NVIDIA GB200 NVL72 and NVIDIA Dynamo Boost Inference Performance for MoE Models', publisher: 'NVIDIA', url: 'https://developer.nvidia.com/blog/how-nvidia-gb200-nvl72-and-nvidia-dynamo-boost-inference-performance-for-moe-models', published: '2025', dated: "Jun 06, 2025", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'epoch-chatgpt-energy': { title: 'How much energy does ChatGPT use?', publisher: 'Epoch AI', url: 'https://epoch.ai/gradient-updates/how-much-energy-does-chatgpt-use', published: '2025', dated: "Feb. 7, 2025", accessed: '09/27/2026', kind: 'primary' },
  'nvidia-hgx-h100-pcf': { title: 'HGX H100 Product Carbon Footprint summary', publisher: 'NVIDIA', url: 'https://images.nvidia.com/aem-dam/Solutions/documents/HGX-H100-PCF-Summary.pdf', published: '2025', dated: "Print code JUL 25 / copyright 2025; PDF created 2025-06-02", accessed: '09/27/2026', kind: 'primary' },
  // real sites and state carbon (research/scenario-sources.md, sections E and F)
  'dcd-fairwater-atlanta': { title: 'Microsoft launches Atlanta Fairwater AI data center: two stories, no UPS or gen-sets', publisher: 'Data Center Dynamics', url: 'https://www.datacenterdynamics.com/en/news/microsoft-launches-atlanta-fairwater-data-center-two-stories-no-ups-or-gen-sets/', published: '2025', dated: "November 12, 2025", accessed: '09/27/2026', via: 'Wayback Machine copy', kind: 'secondary' },
  'microsoft-infinite-scale': { title: 'Infinite scale: The architecture behind the Azure AI superfactory', publisher: 'Microsoft', url: 'https://blogs.microsoft.com/blog/2025/11/12/infinite-scale-the-architecture-behind-the-azure-ai-superfactory/', published: '2025', dated: "Nov 12, 2025", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'dcd-fairwater-wisconsin': { title: 'Microsoft increases Wisconsin data center investment to $7.3bn', publisher: 'Data Center Dynamics', url: 'https://www.datacenterdynamics.com/en/news/microsoft-increases-wisconsin-data-center-investment-to-73bn-says-fairwater-site-will-be-worlds-most-powerful-data-center/', published: '2026', dated: "unknown (search snippet suggests June 18, 2026, unverified)", unchecked: "blocked: 403 live, no Wayback snapshot exists; never independently opened.", kind: 'secondary' },
  'techtimes-fairwater-wisconsin': { title: 'Microsoft Opens Fairwater: Wisconsin AI Campus Runs as One Supercomputer via 800G Ethernet', publisher: 'TechTimes', url: 'https://www.techtimes.com/articles/319205/20260627/microsoft-opens-fairwater-wisconsin-ai-campus-runs-one-supercomputer-via-800g-ethernet.htm', published: '2026', dated: "Jun 27 2026, 11:11 PM EDT", accessed: '09/27/2026', kind: 'secondary' },
  'meta-richland-parish': { title: 'The largest Meta data center yet brings big impact to Louisiana', publisher: 'Meta', url: 'https://datacenters.atmeta.com/richland-parish-data-center/', published: '2024', dated: "unclear (a 'December 2024' figure appears in body text, not confirmed as page date)", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'cnbc-meta-louisiana': { title: "Meta's Louisiana data center investment to reach $50 billion", publisher: 'CNBC', url: 'https://www.cnbc.com/2026/07/13/meta-louisiana-data-center-investment-reaches-50-billion-amid-ai-push.html', published: '2026', dated: "Published Mon, Jul 13 2026 5:30 AM EDT", accessed: '09/27/2026', via: 'Wayback Machine copy', kind: 'secondary' },
  'led-meta-louisiana': { title: 'Meta Commits More Than $50 Billion for North Louisiana Project', publisher: 'Louisiana Economic Development', url: 'https://www.opportunitylouisiana.gov/news/meta-commits-more-than-50-billion-for-north-louisiana-project-becoming-one-of-the-largest-data-centers-in-history', published: '2026', dated: "July 13, 2026", accessed: '09/27/2026', kind: 'primary' },
  'wikipedia-colossus': { title: 'Colossus (data center)', publisher: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Colossus_(data_center)', published: '2026', dated: "Last edited 26 September 2026, 13:32 UTC", accessed: '09/27/2026', kind: 'secondary' },
  'tomshardware-colossus': { title: "Musk's Colossus is fully operational with 200,000 GPUs", publisher: "Tom's Hardware", url: 'https://www.tomshardware.com/tech-industry/artificial-intelligence/musks-colossus-is-fully-operational-with-200-000-gpus-backed-by-tesla-batteries-phase-2-to-consume-300-mw-enough-to-power-300-000-homes', published: '2025', dated: "~May 8, 2025 (via search corroboration; no visible byline date on page)", accessed: '09/27/2026', kind: 'secondary' },
  'eia-state-texas': { title: 'Texas Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/texas/', published: '2025', dated: "Release Date: November 10, 2025", accessed: '09/27/2026', kind: 'primary' },
  'eia-state-tennessee': { title: 'Tennessee Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/tennessee/', published: '2025', dated: "Release Date: November 10, 2025", accessed: '09/27/2026', kind: 'primary' },
  'eia-state-georgia': { title: 'Georgia Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/georgia/', published: '2025', dated: "Release Date: November 10, 2025", accessed: '09/27/2026', kind: 'primary' },
  'eia-state-wisconsin': { title: 'Wisconsin Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/wisconsin/', published: '2025', dated: "Release Date: November 10, 2025", accessed: '09/27/2026', kind: 'primary' },
  'eia-state-louisiana': { title: 'Louisiana Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/louisiana/', published: '2025', dated: "Release Date: November 10, 2025", accessed: '09/27/2026', kind: 'primary' },
  'eia-state-virginia': { title: 'Virginia Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/virginia/', published: '2025', dated: "Release Date: November 10, 2025", accessed: '09/27/2026', kind: 'primary' },
  'eia-state-oregon': { title: 'Oregon Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/oregon/', published: '2025', dated: "Release Date: November 10, 2025", accessed: '09/27/2026', kind: 'primary' },
  'eia-state-washington': { title: 'Washington Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/washington/', published: '2025', dated: "Release Date: November 10, 2025", accessed: '09/27/2026', kind: 'primary' },
  'eia-state-arizona': { title: 'Arizona Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/arizona/', published: '2025', dated: "Release Date: November 10, 2025", accessed: '09/27/2026', kind: 'primary' },
  'eia-state-ohio': { title: 'Ohio Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/ohio/', published: '2025', dated: "Release Date: November 10, 2025", accessed: '09/27/2026', kind: 'primary' },
  'eia-state-iowa': { title: 'Iowa Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/iowa/', published: '2025', dated: "Release Date: November 10, 2025", accessed: '09/27/2026', kind: 'primary' },
  'eia-state-newyork': { title: 'New York Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/newyork/', published: '2025', dated: "Release Date: November 10, 2025", accessed: '09/27/2026', kind: 'primary' },

  // links: copper and optics — the media ladder, the copper wall, cutaway optics (research/copper-optics-sources.md)
  'ieee-25gbe-wiki': { title: '25 Gigabit Ethernet', publisher: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/25_Gigabit_Ethernet', published: '2026', dated: "Last edited 30 June 2026, 22:55 UTC", accessed: '09/27/2026', kind: 'secondary' },
  'ieee-100gbe-wiki': { title: '100 Gigabit Ethernet', publisher: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/100_Gigabit_Ethernet', dated: "unclear - last-edited footer could not be reliably extracted in two attempts", accessed: '09/27/2026', kind: 'secondary' },
  'ieee-8023dj-electrical-adhoc': { title: 'IEEE 802.3dj electrical ad hoc, copper objectives (Ran, Cisco, Apr 2023)', publisher: 'IEEE 802.3', url: 'https://www.ieee802.org/3/dj/public/adhoc/electrical/23_0420/ran_3dj_elec_02_230420.pdf', published: '2023', dated: "20 April 2023", accessed: '09/27/2026', kind: 'primary' },
  'ethernet-alliance-400g-lane': { title: 'Defining the Path to 400 Gbps-per-Lane Ethernet Signaling', publisher: 'Ethernet Alliance', url: 'https://ethernetalliance.org/blog/2026/06/16/defining-the-path-to-400-gbps-per-lane-ethernet-signaling/', published: '2026', dated: "June 16, 2026", accessed: '09/27/2026', kind: 'primary' },
  'photonics-explained-copper-wall': { title: 'Photonics Explained: Copper vs. Photonics', publisher: 'Photonics Explained (Substack)', url: 'https://tacticzhazel.substack.com/p/photonics-explained-copper-vs-photonics', published: '2026', dated: "Apr 11, 2026", accessed: '09/27/2026', kind: 'secondary' },
  'link-pp-8023dj-glossary': { title: 'IEEE 802.3dj glossary', publisher: 'link-pp.com', url: 'https://www.link-pp.com/glossary/ieee-802-3dj.html', published: '2026', dated: "May 27, 2026", accessed: '09/27/2026', kind: 'secondary', marketing: true },
  'photoncap-copper-wall': { title: 'The Copper Wall: Age of Light', publisher: 'photoncap.net', url: 'https://photoncap.net/p/copper-wall-age-of-light-dissecting', published: '2026', dated: "Mar 11, 2026", accessed: '09/27/2026', kind: 'secondary' },
  'wingvc-marvell-copper-wall': { title: 'Light, Radio, and the Race to Replace Copper Interconnects in the AI Era', publisher: 'Wing VC', url: 'https://www.wing.vc/content/light-radio-and-the-race-to-replace-copper-interconnects-in-the-ai-era', published: '2026', dated: "June 2026", accessed: '09/27/2026', kind: 'secondary' },
  'semiengineering-copper-grip-slipping': { title: "Copper's Grip on AI Scaling Is Starting to Slip", publisher: 'SemiEngineering', url: 'https://semiengineering.com/coppers-grip-on-ai-scaling-is-starting-to-slip/', published: '2026', dated: "August 13th, 2026", accessed: '09/27/2026', kind: 'secondary' },
  'nvidia-copper-dac-lacc-overview': { title: 'Copper DAC and LACC Cables Overview', publisher: 'NVIDIA', url: 'https://docs.nvidia.com/networking/display/400g100gpam4ovdev/copper-dac-and-lacc-cables-overview', published: '2025', dated: "Last Updated: November 18, 2025", accessed: '09/27/2026', kind: 'primary' },
  'nvidia-mca4j80n-datasheet': { title: 'MCA4J80-Nxxx active copper cable datasheet', publisher: 'NVIDIA', url: 'https://networking-docs.nvidia.com/mca4j80nxxx800pub', published: '2026', dated: "Last Updated: August 24, 2026", accessed: '09/27/2026', kind: 'primary' },
  'viksnewsletter-acc-power': { title: 'How Rack Power Density Is Opening the ACC Market', publisher: "Vik's Newsletter", url: 'https://www.viksnewsletter.com/p/how-rack-power-density-is-opening-acc-market', published: '2026', dated: "May 25, 2026", accessed: '09/27/2026', kind: 'secondary' },
  'nvidia-linkx-interconnect': { title: 'NVIDIA LinkX Interconnects', publisher: 'NVIDIA', url: 'https://www.nvidia.com/en-us/networking/interconnect/', published: '2026', dated: "Copyright 2026 (no specific update date)", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'credo-zeroflap-aec': { title: 'Credo ZeroFlap AEC product page', publisher: 'Credo', url: 'https://credosemi.com/products/zeroflapaec/', published: '2026', dated: "Copyright 2026 (no specific update date)", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'infraeo-9m-aec-release': { title: 'Infraeo Launches 9m 800G OSFP AEC for Next-Gen AI Infrastructure', publisher: 'Infraeo, via PRWeb', url: 'https://www.prweb.com/releases/infraeo-launches-9m-800g-osfp-aec-for-next-gen-ai-infrastructure-302582943.html', published: '2025', dated: "Oct 15, 2025, 23:13 ET", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'marvell-aec-prnewswire': { title: 'Marvell Expands Interconnect Portfolio with Cloud-Optimized 400G/800G PAM4 DSPs for Active Electrical Cables', publisher: 'Marvell, via PR Newswire', url: 'https://www.prnewswire.com/news-releases/marvell-expands-interconnect-portfolio-with-industrys-1st-cloud-optimized-400g800g-pam4-dsps-for-active-electrical-cables-301493718.html', published: '2022', dated: "Mar 02, 2022, 09:00 ET", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'lpo-msa-lightwave': { title: 'LPO MSA Releases Linear Pluggable Optical Modules Specification', publisher: 'Lightwave Online', url: 'https://www.lightwaveonline.com/home/article/55278631/lpo-msa-releases-linear-pluggable-optical-modules-specification', published: '2025', dated: "March 31, 2025", accessed: '09/27/2026', kind: 'secondary' },
  'semtech-200g-lpo-power-blog': { title: '200G LPO Power, Reach and Loss: Real Numbers', publisher: 'Semtech', url: 'https://blog.semtech.com/200g-lpo-power-reach-and-loss-real-numbers', published: '2026', dated: "18 August, 2026", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'semtech-lpo-ai-basics-blog': { title: 'AI Data Center Basics: What Is Linear Pluggable Optics?', publisher: 'Semtech', url: 'https://blog.semtech.com/ai-data-center-basics-what-is-linear-pluggable-optics-lpo', published: '2026', dated: "04 August, 2026", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'ascentoptics-800g-lpo-guide': { title: '800G LPO Guide (2026)', publisher: 'AscentOptics', url: 'https://ascentoptics.com/blog/800g-lpo/', published: '2026', dated: "September 11, 2026", accessed: '09/27/2026', kind: 'secondary', marketing: true },
  'cisco-400g-qsfpdd-datasheet': { title: '400G QSFP-DD datasheet', publisher: 'Cisco', url: 'https://www.cisco.com/c/en/us/products/collateral/interfaces-modules/transceiver-modules/datasheet-c78-743172.html', published: '2026', dated: "Date Updated: March 3, 2026", accessed: '09/27/2026', kind: 'primary' },
  'semianalysis-cpo-newsletter': { title: 'Co-Packaged Optics (CPO): The Book on Scaling', publisher: 'SemiAnalysis', url: 'https://newsletter.semianalysis.com/p/co-packaged-optics-cpo-book-scaling', published: '2026', dated: "Jan 01, 2026", accessed: '09/27/2026', kind: 'secondary' },
  'broadcom-sian3-200g-lane-dsp': { title: 'Broadcom Extends 200G-Lane DSP PHY Leadership for Next-Generation AI Infrastructure', publisher: 'Broadcom, via GlobeNewswire', url: 'https://www.globenewswire.com/news-release/2025/03/25/3048831/19933/en/broadcom-extends-200g-lane-dsp-phy-leadership-for-next-generation-ai-infrastructure.html', published: '2025', dated: "March 25, 2025 09:00 ET", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'marvell-ara-1-6t-prnewswire': { title: "Marvell Unveils Industry's First 3nm 1.6 Tbps PAM4 Interconnect Platform", publisher: 'Marvell, via PRNewswire', url: 'https://www.prnewswire.com/news-releases/marvell-unveils-industrys-first-3nm-1-6-tbps-pam4-interconnect-platform-to-scale-accelerated-infrastructure-302320829.html', published: '2024', dated: "Dec 03, 2024, 09:00 ET", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'nextplatform-broadcom-cpo': { title: 'The Third Time Will Be the Charm for Broadcom Switch Co-Packaged Optics', publisher: 'The Next Platform', url: 'https://www.nextplatform.com/2025/10/17/the-third-time-will-be-the-charm-for-broadcom-switch-co-packaged-optics/', published: '2025', dated: "Fri 17 Oct 2025 16:57 UTC", accessed: '09/27/2026', kind: 'secondary' },
  'micasnetworks-51-2t-release': { title: 'Micas Networks 51.2T CPO system reaches volume production', publisher: 'Micas Networks', url: 'https://micasnetworks.com/company/news/30202', published: '2025', dated: "2025-03-18 (dateline reads March 17, 2025)", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'storagereview-nvidia-cpo-production': { title: 'NVIDIA Spectrum-X Ethernet Photonics Enters Full Production', publisher: 'StorageReview', url: 'https://www.storagereview.com/news/nvidia-spectrum-x-ethernet-photonics-enters-full-production-with-4x-fewer-lasers-and-a-five-vendor-cpo-supply-chain', published: '2026', dated: "August 15, 2026", accessed: '09/27/2026', kind: 'secondary' },
  'broadcom-davisson-servethehome': { title: 'Broadcom Tomahawk 6 "Davisson" 102.4T Switch with Co-Packaged Optics Shipping', publisher: 'ServeTheHome', url: 'https://www.servethehome.com/broadcom-tomahawk-6-davisson-102-4t-switch-with-co-packaged-optics-shipping/', published: '2025', dated: "October 12, 2025", accessed: '09/27/2026', kind: 'secondary' },
  'lcom-lr4-10km': { title: 'LR4 Optics Solutions: 10km Long-Haul Data Center Links', publisher: 'L-Com', url: 'https://www.l-p.com/blog/use-cases-solutions/lr4-optics-solutions-10km-long-haul-data-center-links.htm', published: '2026', dated: "June 03, 2026", accessed: '09/27/2026', kind: 'secondary', marketing: true },
  'nvidia-dgx-gb200-user-guide': { title: 'DGX GB200 User Guide, hardware overview', publisher: 'NVIDIA', url: 'https://docs.nvidia.com/dgx/dgxgb200-user-guide/hardware.html', published: '2026', dated: "Last Updated: September 17, 2026", accessed: '09/27/2026', kind: 'primary' },
  'arxiv-2601-14342': { title: "VCSEL-based CPO for Scale-Up in A.I. Datacenter. Status and Perspectives", publisher: 'arXiv', url: 'https://arxiv.org/abs/2601.14342', published: '2026', dated: "Submitted Tue, 20 Jan 2026 15:16:01 UTC", accessed: '09/27/2026', kind: 'primary' },

  // ---- optics workstream (2026-09-27 audit pass, findings 1/3/5/18c/18g): OIF's own 400ZR reach figures,
  // separating direct-detect campus optics (LR4) from coherent DCI, and the NVIDIA CPO laser-module count ----
  'oif-400zr-ia': { title: 'Implementation Agreement 400ZR (OIF-400ZR-02.0)', publisher: 'Optical Internetworking Forum (OIF)', url: 'https://www.oiforum.com/wp-content/uploads/OIF-400ZR-02.0.pdf' },
  'edgeoptic-400g-coherent-guide': { title: '400G Coherent Optics Guide: ZR, ZR+ & MZR Comparison', publisher: 'EDGE Optical Solutions', url: 'https://edgeoptic.com/kb_article/deep-dive-400g-coherent-optics-guide', accessed: '09/27/2026', kind: 'secondary', marketing: true },
  'ieee-spectrum-cpo-nvidia': { title: 'Nvidia Unveils Game-Changing Optical Network Switch', publisher: 'IEEE Spectrum', url: 'https://spectrum.ieee.org/co-packaged-optics', accessed: '09/27/2026', kind: 'secondary' },

  // ---- optics review pass (2026-09-27, finding 18g): NVIDIA's own account of the external-laser-source
  // module count, reconciling the "one laser per eight links" figure the audit found unsourced ----
  'nvidia-cpo-industry-collaboration-blog': { title: 'How Industry Collaboration Fosters NVIDIA Co-Packaged Optics', publisher: 'NVIDIA', url: 'https://developer.nvidia.com/blog/how-industry-collaboration-fosters-nvidia-co-packaged-optics/' },

  // engine workstream, 2026-09-27 audit pass (issues 4, 9, 10, 14, 15, 18a, 18b)
  'nvidia-dsx-data-center-architecture': { title: 'DSX architecture: data center reference architecture (GB200/GB300 compute tray network interfaces)', publisher: 'NVIDIA', url: 'https://docs.nvidia.com/dsx/ncp/software-reference-guide/data-center-architecture' },
  'nvidia-coreweave-gb200-400g': { title: 'NVIDIA GB200 NVL72 on CoreWeave: Quantum-2 InfiniBand at 400 Gb/s per GPU', publisher: 'NVIDIA', url: 'https://blogs.nvidia.com/blog/blackwell-coreweave-gb200-nvl72-instances-cloud/' },
  'ocp-hgx-baseboard-spec': { title: 'HGX Form Factor Specification (54.0 V nominal baseboard power rail)', publisher: 'Open Compute Project', url: 'https://www.opencompute.org/documents/open-compute-specification-hgx-baseboard-contribution-r1-v0-1-pdf' },
  // the exact 13,386/26,156 tok/s figures are LMSYS/SGLang's own GB200 deployment benchmark, not a SemiAnalysis
  // InferenceMAX result (a later LMSYS post links this one but only restates the numbers rounded)
  'lmsys-sglang-gb200-part2': { title: 'Deploying DeepSeek on GB200 NVL72 with PD and Large Scale EP (Part II): 3.8x Prefill, 4.8x Decode Throughput', publisher: 'LMSYS Org', url: 'https://www.lmsys.org/blog/2025-09-25-gb200-part-2/' },
  'nvidia-quantum2-qm9700-specs': { title: 'Quantum-2 QM9700 specifications (64 × 400G NDR)', publisher: 'NVIDIA', url: 'https://docs.nvidia.com/networking/display/qm97x0pub/specifications' },

  // energy workstream (2026-09-27 audit review): the primary sources behind the IT-energy WUE
  // denominator fix and the NFPA 110 Type/Level wording fix
  'green-grid-wue-wp35': { title: 'Water Usage Effectiveness (WUE): A Green Grid Data Center Sustainability Metric (White Paper #35)', publisher: 'The Green Grid', url: 'https://www.thegreengrid.org/system/files/store/WUE_v1.pdf' },
  'cummins-nfpa110-ate': { title: "Ask the Experts: NFPA 110 for Emergency Power Systems", publisher: 'Cummins', url: 'https://www.cummins.com/sites/default/files/2021-04/AtE-NFPA110_EXT_3.25.21.pdf' },

  // content workstream (audit item 18h, 09/27/2026): copper-in-cube vs OCS-between-cubes on the TPU card
  'google-ironwood-codesign': { title: 'Inside the Ironwood TPU codesigned AI stack', publisher: 'Google Cloud', url: 'https://cloud.google.com/blog/products/compute/inside-the-ironwood-tpu-codesigned-ai-stack' },

  // ---- traced 09/27/2026: level 1, Scale across, and the real campuses ----


  // ---- traced 09/27/2026: level 2, Grid & campus, and the clock notes ----


  // ---- traced 09/27/2026: level 3, the data hall, the ledger and the inventory ----


  // ---- traced 09/27/2026: levels 4 and 5, the rack and the compute tray ----


  // ---- traced 09/27/2026: level 6, the GPU package, and the links ladder ----
  'nvidia-hopper-architecture-indepth': { title: 'NVIDIA Hopper Architecture In-Depth', publisher: 'NVIDIA', url: 'https://developer.nvidia.com/blog/nvidia-hopper-architecture-in-depth/', published: '03/22/2022', accessed: '09/27/2026', kind: 'primary', marketing: true },
  'techinsights-h100-cowos-s': { title: 'NVIDIA H100 Hopper TSMC CoWoS-S Flip Chip Ball Grid Array', publisher: 'TechInsights', url: 'https://www.techinsights.com/blog/nvidia-h100-hopper-tsmc-cowos-s-flip-chip-ball-grid-array', accessed: '09/27/2026', unchecked: "opened directly and via Wayback (2023/2024/2025 snapshots + live 2026): the page is only a paid-report landing page (\"Read the full report\"); no body text states the 7-die/CoWoS-S, 814mm2 or 6-stack HBM figures a prior pass quoted from it. No longer cited by any level-6 claim (moved to tomshardware-cowos-l-blackwell, nvidia-hopper-architecture-indepth and tomshardware-hynix-hbm3-h100 below) — left here in case a future pass finds a working mirror.", kind: 'secondary' },
  'tomshardware-hynix-hbm3-h100': { title: 'SK Hynix Kicks Off HBM3 Mass Production, Ships to Nvidia', publisher: "Tom's Hardware", url: 'https://www.tomshardware.com/news/sk-hynix-kicks-off-hbm-3-mass-production-ships-to-nvidia', accessed: '09/27/2026', kind: 'secondary' },
  'nvidia-h100-product-page': { title: 'H100 GPU', publisher: 'NVIDIA', url: 'https://www.nvidia.com/en-us/data-center/h100/', published: '2026', dated: "unknown; generic copyright only, no page-specific date", accessed: '09/27/2026', kind: 'primary', marketing: true },
  'nvidia-photonics-switching-blog': { title: 'A New Era in Data Center Networking with NVIDIA Silicon Photonics-based Network Switching', publisher: 'NVIDIA', url: 'https://developer.nvidia.com/blog/a-new-era-in-data-center-networking-with-nvidia-silicon-photonics-based-network-switching/', accessed: '09/27/2026', kind: 'primary', marketing: true },
  'nvidianews-blackwell-platform-arrival': { title: 'NVIDIA Blackwell Platform Arrives to Power a New Era of Computing', publisher: 'NVIDIA Newsroom', url: 'https://nvidianews.nvidia.com/news/nvidia-blackwell-platform-arrives-to-power-a-new-era-of-computing', published: '03/18/2024', accessed: '09/27/2026', kind: 'primary', marketing: true },
  'tomshardware-cowos-l-blackwell': { title: 'Nvidia shifts to CoWoS-L packaging for Blackwell GPU production ramp-up', publisher: "Tom's Hardware", url: 'https://www.tomshardware.com/tech-industry/nvidia-shifts-to-cowos-l-packaging-for-blackwell-gpu-production-ramp-up', accessed: '09/27/2026', kind: 'secondary' },
  'wccftech-rubin-gpu-architecture': { title: 'NVIDIA Rubin GPUs Bring 10x Increase in Agentic AI Performance Versus Blackwell as Its Architecture Gets Fully Unpacked, Featuring 336 Billion Transistors', publisher: 'WCCFTech', url: 'https://wccftech.com/nvidia-rubin-gpu-architecture/', accessed: '09/27/2026', kind: 'secondary' },
  'nvidia-rubin-gpu-architecture-blog': { title: 'Inside NVIDIA Rubin GPU Architecture: Powering the Era of Agentic AI', publisher: 'NVIDIA', url: 'https://developer.nvidia.com/blog/inside-nvidia-rubin-gpu-architecture-powering-the-era-of-agentic-ai/', accessed: '09/27/2026', kind: 'primary', marketing: true },
  'semianalysis-inferencex-inferencemax': { title: 'InferenceMAX: Open Source Inference Benchmarking', publisher: 'SemiAnalysis / InferenceX', url: 'https://inferencex.semianalysis.com/blog/inferencemax-open-source-inference-benchmarking', accessed: '09/27/2026', kind: 'secondary' },
  'ascentoptics-coherent-power': { title: 'Coherent Optical Module Power Consumption: Complete Guide for Network Engineers', publisher: 'AscentOptics', url: 'https://ascentoptics.com/blog/coherent-optical-module-power-consumption/', accessed: '09/27/2026', kind: 'secondary', marketing: true },

  // ---- traced 09/27/2026: the glossary, the method page and prose claims ----


};

// PART_SOURCES: which sources back the specs on each card. Key = '<layer>:<sceneId>:<partId>',
// layer is 'power' | 'data' | 'heat'. Empty array = the card is estimate-only, no source to cite.
export const PART_SOURCES = {
  // ---- power ----
  'power:across:carbon': ['eia-state-texas', 'eia-state-tennessee', 'eia-state-georgia', 'eia-state-wisconsin', 'eia-state-louisiana', 'eia-state-washington', 'eia-co2-per-kwh'],
  'power:across:site-abilene': ['epoch-dc-abilene', 'epoch-stargate-abilene'],
  'power:across:site-colossus1': ['compute-atlas-colossus', 'epoch-dc-colossus2', 'epoch-largest-dc', 'wikipedia-colossus', 'tomshardware-colossus', 'semianalysis-xai-colossus2'],
  'power:across:site-fairwater-atl': ['epoch-dc-fairwater-atl', 'microsoft-infinite-scale', 'dcd-fairwater-atlanta', 'datacenterfrontier-fairwater'],
  'power:across:site-fairwater-wi': ['epoch-dc-fairwater-wi', 'dcd-fairwater-wisconsin', 'techtimes-fairwater-wisconsin'],
  'power:across:site-rainier': ['epoch-dc-new-carlisle', 'eia-state-indiana', 'measuredai-new-carlisle', 'compute-atlas-rainier', 'blackridge-rainier'],
  'power:across:site-prometheus': ['epoch-dc-prometheus', 'epoch-satellite-prometheus', 'mlq-meta-gas-tents', 'measuredai-prometheus-primer', 'eia-state-ohio', 'techcrunch-meta-tents'],
  'power:across:site-hyperion': ['epoch-dc-hyperion', 'meta-richland-parish', 'cnbc-meta-louisiana', 'led-meta-louisiana'],
  'power:across:grid': ['ieee-spectrum-hyperion', 'epoch-stargate-abilene'],
  'power:across:plants': ['eia-td-losses'],
  'power:across:home': [],

  'power:campus:line': ['eia-td-losses', 'epoch-stargate-abilene'],
  'power:campus:substation': [],
  'power:campus:mpt': ['pa-transformer-345kv', 'transformer-lead-times'],
  'power:campus:ehouse': ['mv-distribution-atk'],
  'power:campus:gensets': ['cummins-dqkan-genset', 'cummins-qsk78', 'cat-c175-16'],
  'power:campus:fuel': ['cummins-dqkan-genset'],
  'power:campus:bess': ['nvidia-bess-blog', 'dcd-xai-colossus-memphis'],
  'power:campus:unitsubs': ['doe-transformer-efficiency'],
  'power:campus:hall': [],
  'power:campus:drycoolers': ['ashrae-liquid-cooling-classes', 'introl-wue', 'evapco-apex', 'bac-data-centers'],
  'power:campus:chillers': ['schneider-uniflair'],
  'power:campus:towers': ['introl-wue', 'nrel-water-electricity', 'green-grid-wue-wp35'],
  'power:campus:fiber': ['zayo-route-diversity'],

  'power:hall:unitsub': ['doe-transformer-efficiency'],
  'power:hall:swgr': [],
  'power:hall:sst': ['navitas-800vdc', 'nvidia-800v-hvdc', 'delta-ocp-800vdc', 'infineon-solaredge-sst'],
  'power:hall:ups': ['eaton-9395xr-ups'],
  'power:hall:batt': [],
  'power:hall:busway': ['lv-distribution-busway', 'nvidia-800v-hvdc'],
  'power:hall:racks': ['nvidia-gb200-nvl72', 'hpe-gb200-quickspecs', 'nvidia-dgx-h100'],
  'power:hall:containment': [],
  'power:hall:inrow': [],
  'power:hall:cdu': ['vertiv-coolchip-cdu', 'motivair-cdu-brochure'],
  'power:hall:fwater': [],
  'power:hall:fanwall': [],
  'power:hall:network': [],

  'power:rack:feed': [],
  'power:rack:shelves': ['navitas-800vdc', 'nvidia-gb200-ocp', 'liteon-gb200-power-system', 'delta-ocp-800vdc', 'liteon-gtc-2026'],
  'power:rack:busbar': ['nvidia-gb200-ocp', 'nvidia-800v-hvdc'],
  'power:rack:compute': ['nvidia-gb200-nvl72'],
  'power:rack:nvswitch': ['nvidia-nvl72-reference-arch'],
  'power:rack:spine': ['nvidia-gb200-ocp', 'servethehome-dgx-gb200', 'nvidia-dgx-gb200-user-guide', 'viksnewsletter-acc-power', 'arxiv-2601-14342'],
  'power:rack:manifold': [],
  'power:rack:pdu': [],
  'power:rack:servers': ['nvidia-dgx-h100', 'nvidia-h100-datasheet'],
  'power:rack:psus': ['fs-com-dgx-h100'],
  'power:rack:cabling': [],
  'power:rack:mgmt': [],

  'power:tray:clip': [],
  'power:tray:ibc': ['semianalysis-blackwell-power-delivery'],
  'power:tray:vrm': ['semianalysis-blackwell-power-delivery'],
  'power:tray:gpu': ['nvidia-gb200-nvl72', 'nvidia-gb300-nvl72', 'nvidia-h100-datasheet'],
  'power:tray:grace': ['nvidia-gb200-nvl72'],
  'power:tray:lpddr': ['nvidia-gb200-nvl72'],
  'power:tray:coldplates': [],
  'power:tray:nic': ['nvidia-dsx-data-center-architecture', 'nvidia-coreweave-gb200-400g', 'nvidia-connectx8-datasheet', 'nvidia-gb300-nvl72', 'nvidia-dpu-supernic', 'nvidia-bluefield-datasheet'],
  'power:tray:nvconn': ['nvidia-gb200-nvl72'],
  'power:tray:psu': ['fs-com-dgx-h100'],
  'power:tray:cpu': [],
  'power:tray:heatsinks': [],
  'power:tray:nvswitch': ['nvidia-h100-datasheet'],

  'power:chip:balls': ['semianalysis-blackwell-power-delivery'],
  'power:chip:interposer': ['nvidia-blackwell-ultra-blog', 'wccftech-nv-hbi'],
  'power:chip:dies': ['nvidia-blackwell-ultra-blog', 'wccftech-nv-hbi'],
  'power:chip:hbm': ['micron-hbm3e-brief', 'arxiv-gpu-power-visibility', 'skhynix-hbm4', 'micron-hbm4', 'samsung-hbm4'],
  'power:chip:tokens': ['google-inference-impact', 'samsi-words-to-watts'],

  // ---- data ----
  'data:across:dci': ['ciena-wavelogic6', 'marvell-colorz-800', 'ciena-wavelogic6-nano'],
  'data:across:ila': [],
  'data:across:route': ['microsoft-hollow-core-fiber', 'coherent-full-cband-pols'],
  'data:across:remote': ['microsoft-ai-wan', 'nvidia-spectrum-xgs', 'deepmind-decoupled-diloco'],
  'data:across:home': [],

  'data:campus:fiber': ['zayo-route-diversity'],
  'data:campus:dci': ['ciena-wavelogic6'],
  'data:campus:interhall': [],
  'data:campus:ductbank': ['prysmian-flexribbon'],
  'data:campus:hall': [],
  'data:campus:longhaul': [],

  'data:hall:odf': ['corning-edge8'],
  'data:hall:crosshall': [],
  'data:hall:pp': ['meta-llama3-herd-parallelism'],
  'data:hall:dp': ['meta-llama3-herd-parallelism', 'deepseek-v3-technical-report'],
  'data:hall:uplinks': [],
  'data:hall:leaf': ['nvidia-quantum2-qm9700-specs', 'nvidia-sn5000-datasheet', 'nvidia-quantum-x800-switches', 'nvidia-rubin-platform'],
  'data:hall:spine': ['nvidia-quantum2-qm9700-specs', 'nvidia-xdr-switch-specs', 'nvidia-rubin-platform', 'broadcom-tomahawk6', 'marvell-teralynx10'],
  'data:hall:runways': [],
  'data:hall:optics': ['nvidia-800g-dr8-datasheet', 'innolight-1p6t', 'coherent-1p6t-dr8', 'marvell-ara-1p6t-portfolio', 'broadcom-sian3-200g-lane-dsp', 'credo-bluebird-dsp'],
  'data:hall:cpo': ['nvidia-spectrum-x-cpo', 'broadcom-davisson-cpo', 'storagereview-nvidia-cpo-production'],
  'data:hall:racks': ['nvidia-gb200-nvl72'],

  'data:rack:tp': ['meta-llama3-herd-parallelism'],
  'data:rack:nvswitch': ['nvidia-nvl72-reference-arch'],
  'data:rack:spine': ['nvidia-gb200-ocp', 'servethehome-dgx-gb200', 'nvidia-dgx-gb200-user-guide', 'viksnewsletter-acc-power', 'arxiv-2601-14342'],
  'data:rack:optical': ['google-ironwood-tpu', 'google-ironwood-codesign'],
  'data:rack:uplinks': ['nvidia-h100-datasheet'],
  'data:rack:compute': [],
  'data:rack:mgmt': [],
  'data:rack:servers': ['nvidia-h100-datasheet'],

  'data:tray:nvconn': ['nvidia-gb200-nvl72'],
  'data:tray:c2c': ['nvidia-gb200-nvl72', 'naddod-gb200-interconnect'],
  'data:tray:cx': ['nvidia-dsx-data-center-architecture', 'nvidia-coreweave-gb200-400g', 'nvidia-connectx8-datasheet', 'fs-com-dgx-h100'],
  'data:tray:osfp': ['nvidia-800g-dr8-datasheet'],
  'data:tray:dpu': ['nvidia-dgx-gb200-hardware', 'nvidia-bluefield4-datasheet'],
  'data:tray:gpu': [],
  'data:tray:nvswitch': ['nvidia-h100-datasheet'],
  'data:tray:pcie': [],

  'data:chip:hbm': ['micron-hbm3e-brief'],
  'data:chip:hbi': ['wccftech-nv-hbi'],
  'data:chip:nvphy': [],
  'data:chip:cpo': ['nvidia-spectrum-x-cpo'],
  'data:chip:tokens': [],

  // ---- heat ----
  'heat:across:climate': [],
  'heat:across:home': [],

  'heat:campus:drycoolers': ['ashrae-liquid-cooling-classes', 'alliance-chemical-gpu-thermal'],
  'heat:campus:chillers': [],
  'heat:campus:towers': ['introl-wue', 'nrel-water-electricity', 'green-grid-wue-wp35'],
  'heat:campus:plume': [],
  'heat:campus:reuse': ['fortum-finland-heat', 'munters-odense', 'stockholm-data-parks'],

  'heat:hall:inrow': [],
  'heat:hall:cdu': ['vertiv-coolchip-cdu', 'motivair-cdu-brochure'],
  'heat:hall:fwater': [],
  'heat:hall:hotaisle': [],
  'heat:hall:fanwall': [],
  'heat:hall:riser': [],

  'heat:rack:manifold': ['alliance-chemical-gpu-thermal'],
  'heat:rack:rearair': [],
  'heat:rack:compute': [],
  'heat:rack:front': [],
  'heat:rack:servers': [],

  'heat:tray:coldplates': [],
  'heat:tray:gpuheat': [],
  'heat:tray:fans': [],
  'heat:tray:qd': [],
  'heat:tray:heatsinks': [],

  'heat:chip:junction': [],
  'heat:chip:flux': ['alliance-chemical-gpu-thermal'],
  'heat:chip:tim': [],
  'heat:chip:hbm': ['micron-hbm3e-brief'],

  // ---- links: the media ladder, the copper wall, cutaway optics (3.2 · Links) ----
  'links:dac': ['ieee-25gbe-wiki', 'ieee-100gbe-wiki', 'ieee-8023dj-electrical-adhoc', 'ethernet-alliance-400g-lane', 'photonics-explained-copper-wall', 'link-pp-8023dj-glossary', 'photoncap-copper-wall'],
  'links:acc': ['nvidia-copper-dac-lacc-overview', 'nvidia-mca4j80n-datasheet', 'viksnewsletter-acc-power', 'ieee-8023dj-electrical-adhoc'],
  'links:aec': ['nvidia-linkx-interconnect', 'credo-zeroflap-aec', 'infraeo-9m-aec-release', 'viksnewsletter-acc-power', 'marvell-aec-prnewswire', 'ieee-8023dj-electrical-adhoc', 'marvell-alaska-a-aec', 'credo-hiwire-800g-aec', 'astera-taurus-scm'],
  'links:lpo': ['lpo-msa-lightwave', 'semtech-200g-lpo-power-blog', 'semtech-lpo-ai-basics-blog', 'ascentoptics-800g-lpo-guide'],
  'links:dsp': ['cisco-400g-qsfpdd-datasheet', 'semianalysis-cpo-newsletter', 'broadcom-sian3-200g-lane-dsp', 'marvell-ara-1-6t-prnewswire', 'marvell-ara-1p6t-portfolio', 'credo-bluebird-dsp'],
  'links:lr4': ['cisco-400g-qsfpdd-datasheet', 'lcom-lr4-10km'],
  'links:cpo': ['nvidia-spectrum-x-cpo', 'broadcom-davisson-cpo', 'nextplatform-broadcom-cpo', 'micasnetworks-51-2t-release', 'storagereview-nvidia-cpo-production', 'broadcom-davisson-servethehome'],
  'links:coherent': ['ciena-wavelogic6', 'oif-400zr-ia', 'edgeoptic-400g-coherent-guide', 'marvell-colorz-800', 'ciena-wavelogic6-nano'],
  'links:copperwall': ['ieee-25gbe-wiki', 'ieee-100gbe-wiki', 'ieee-8023dj-electrical-adhoc', 'ethernet-alliance-400g-lane', 'photonics-explained-copper-wall', 'link-pp-8023dj-glossary', 'photoncap-copper-wall', 'wingvc-marvell-copper-wall', 'semiengineering-copper-grip-slipping'],
  'links:cutaway-dsp': ['cisco-400g-qsfpdd-datasheet', 'semianalysis-cpo-newsletter', 'broadcom-sian3-200g-lane-dsp'],
  'links:cutaway-lpo': ['semtech-200g-lpo-power-blog', 'ascentoptics-800g-lpo-guide'],
  'links:cutaway-cpo': ['nvidia-spectrum-x-cpo', 'broadcom-davisson-cpo', 'broadcom-davisson-servethehome'],
};

// LEDGER_SOURCES: [labelPrefix, sourceIds] pairs, matched with row.label.startsWith(prefix).
export const LEDGER_SOURCES = [
  ['Main power transformers', ['pa-transformer-345kv', 'transformer-lead-times']],
  ['Campus cables & switchgear', []],
  ['Unit substations', ['doe-transformer-efficiency']],
  ['Solid-state transformers', ['navitas-800vdc', 'nvidia-800v-hvdc']],
  ['800 V DC bus & batteries', ['nvidia-800v-hvdc']],
  ['UPS, double conversion', ['eaton-9395xr-ups']],
  ['Busway & whips', ['lv-distribution-busway', 'nvidia-800v-hvdc']],
  ['Cooling:', ['ashrae-liquid-cooling-classes', 'introl-wue']],
  ['Lighting, controls, offices', []],
  ['Scale-out switches', ['nvidia-quantum2-qm9700-specs', 'nvidia-xdr-switch-specs']],
  ['Optical transceivers', ['nvidia-800g-dr8-datasheet']],
  ['In-rack DC-DC', ['navitas-800vdc']],
  ['Server power supplies', ['fs-com-dgx-h100']],
  ['Rack power shelves', ['liteon-gb200-power-system', 'nvidia-gb200-ocp']],
  ['Server power cabling', []],
  ['Busbar', ['nvidia-gb200-ocp']],
  ['NVSwitch chips', ['nvidia-h100-datasheet']],
  ['NVLink switch trays', ['nvidia-nvl72-reference-arch']],
  ['x86 CPUs', []],
  ['Grace CPUs', ['nvidia-gb200-nvl72']],
  ['Vera CPUs', []],
  ['NICs & DPUs', ['fs-com-dgx-h100']],
  ['SuperNICs & DPUs', ['nvidia-connectx8-datasheet']],
  ['SSDs, fans, management', []],
  ['Bus converters', ['semianalysis-blackwell-power-delivery']],
  ['Voltage regulators', ['semianalysis-blackwell-power-delivery']],
  ['HBM', ['micron-hbm3e-brief']],
  // engine workstream, issue 14: the spare-capacity row is the model's own rounding artifact, not an external fact
  ['Unallocated', []],
];

// EST_NOTES: one sentence on how an estimate was derived, only where data.js's own formula
// or the research notes actually say so.
export const EST_NOTES = {
  'power:campus:line': 'Per-phase current from campus MW ÷ (√3 × 345 kV × 0.95 assumed power factor).',
  'power:campus:fuel': 'Tanker count from the 48-hour fuel volume ÷ 30,000 L per truckload.',
  'power:hall:unitsub': 'Secondary current from 2.5 MVA ÷ (√3 × 480 V × 0.95 assumed power factor).',
  'power:hall:busway': 'Per-rack current from rack kW ÷ (√3 × 415 V × 0.95 assumed power factor).',
  'power:hall:racks': 'Liquid/air kW split from the rack total × HPE\'s published liquid share for this rack.',
  'power:rack:busbar': 'Busbar current from the rack DC bus power ÷ 50 V.',
  'power:chip:balls': 'Core current from GPU power (minus HBM share) ÷ 0.8 V assumed core voltage.',
  'power:tray:vrm': 'Core current from GPU power (minus HBM share) ÷ 0.8 V assumed core voltage.',
  'heat:chip:flux': 'Average flux from GPU power (minus HBM share) ÷ die area; hot spots run well above this average.',
  'heat:tray:fans': 'Airflow from rack heat, air density and specific heat at a 15 °C rise (Q = ṁ·cp·ΔT).',
};
