// Sources for the "source popovers" on basis chips. SOURCES holds the reusable citations;
// PART_SOURCES and LEDGER_SOURCES point each card / ledger row at the citations behind it;
// EST_NOTES explains, in one sentence, how a handful of estimates were derived. Every URL
// here appears verbatim in research/*.md or in the footer of index.html — never invented.

export const SOURCES = {
  // grid, campus, transformers, generators
  'eia-td-losses': { title: 'How much electricity is lost in electricity transmission and distribution', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/tools/faqs/faq.php?id=105&t=5' },
  'eia-co2-per-kwh': { title: 'How much carbon dioxide is produced per kilowatthour of U.S. electricity generation', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/tools/faqs/faq.php?id=74&t=11' },
  'epoch-stargate-abilene': { title: 'OpenAI Stargate: where the US sites stand', publisher: 'Epoch AI', url: 'https://epoch.ai/publications/openai-stargate-where-the-us-sites-stand' },
  'epoch-dc-abilene': { title: 'OpenAI Stargate Abilene, Frontier Data Centers (updated 09/24/2026)', publisher: 'Epoch AI', url: 'https://epoch.ai/data/ai-data-centers/directory/openai-stargate-abilene' },
  'epoch-dc-colossus2': { title: 'xAI Colossus 2, Frontier Data Centers (updated 09/24/2026)', publisher: 'Epoch AI', url: 'https://epoch.ai/data/ai-data-centers/directory/colossus-2' },
  'epoch-dc-fairwater-atl': { title: 'Microsoft Fairwater Atlanta, Frontier Data Centers (updated 09/24/2026)', publisher: 'Epoch AI', url: 'https://epoch.ai/data/ai-data-centers/directory/microsoft-fairwater-atlanta' },
  'epoch-dc-fairwater-wi': { title: 'Microsoft Fairwater Wisconsin, Frontier Data Centers (updated 09/24/2026)', publisher: 'Epoch AI', url: 'https://epoch.ai/data/ai-data-centers/directory/microsoft-fairwater-wisconsin' },
  'epoch-dc-hyperion': { title: 'Meta Hyperion, Frontier Data Centers', publisher: 'Epoch AI', url: 'https://epoch.ai/data/ai-data-centers/directory/meta-hyperion' },
  'epoch-largest-dc': { title: 'Largest AI data centers by power capacity (updated 09/24/2026)', publisher: 'Epoch AI', url: 'https://epoch.ai/graphs/largest-ai-data-centers-by-power-capacity' },
  'compute-atlas-colossus': { title: 'xAI Colossus, Memphis, TN (checked 09/23/2026)', publisher: 'Compute Atlas', url: 'https://www.compute-atlas.com/facilities/xai-colossus-memphis-tn' },
  'ieee-spectrum-hyperion': { title: '5GW Data Center Buildout Requires Novel Engineering', publisher: 'IEEE Spectrum', url: 'https://spectrum.ieee.org/5gw-data-center' },
  'dcd-xai-colossus-memphis': { title: "Fury from campaigners as Elon Musk's xAI gets 150MW for Colossus supercomputer in Memphis", publisher: 'Data Center Dynamics', url: 'https://www.datacenterdynamics.com/en/news/xai-colossus-memphis-power-tva/' },
  'semianalysis-xai-colossus2': { title: "xAI's Colossus 2 — First Gigawatt Datacenter", publisher: 'SemiAnalysis', url: 'https://newsletter.semianalysis.com/p/xais-colossus-2-first-gigawatt-datacenter' },
  'pa-transformer-345kv': { title: '345 kV Power Transformer Projects', publisher: 'PA Transformer', url: 'https://www.patransformer.com/power-transformer-projects/power-transformer-345-kv/' },
  'transformer-lead-times': { title: 'HV Transformer Lead Times 2026: EU vs US', publisher: 'GridReadiness', url: 'https://www.gridreadiness.com/blog/power-transformer-lead-times-ai-data-center-2026.html' },
  'doe-transformer-efficiency': { title: 'Energy Conservation Standards for Distribution Transformers, final rule', publisher: 'U.S. Department of Energy', url: 'https://www1.eere.energy.gov/buildings/appliance_standards/pdfs/dt_final_rule.pdf' },
  'mv-distribution-atk': { title: 'Medium-Voltage Distribution for Data Center Campuses in 2026', publisher: 'ATK Energy Group', url: 'https://atkenergygroup.com/blog/medium-voltage-distribution-data-center-campuses/' },
  'cummins-dqkan-genset': { title: 'DQKAN 2.5 MW generator data sheet', publisher: 'Cummins', url: 'https://www.globalpwr.com/wp-content/uploads/cut-sheets/gps-cummins-2500-kw-dqkan-data-sheet.pdf' },
  'nvidia-bess-blog': { title: 'Designing Production-Ready Battery Energy Storage Systems for AI Factories', publisher: 'NVIDIA', url: 'https://developer.nvidia.com/blog/designing-production-ready-battery-energy-storage-systems-for-ai-factories' },
  'lv-distribution-busway': { title: 'LV Distribution: Busway, PDUs, RPPs & Rack Power', publisher: 'The Definitive Guide to AI Data Centers', url: 'https://aidatacenterguide.com/part-4-electrical-and-energy-infrastructure/4-6-lv-distribution-busway-pdus-rpps-and-rack-power' },
  'zayo-route-diversity': { title: "Zayo's Unique Long-Haul Routes, setting the standard for network resilience", publisher: 'Zayo', url: 'https://www.zayo.com/info/zayos-unique-long-haul-routes-setting-the-standard-for-network-resilience/' },

  // cooling and water
  'ashrae-liquid-cooling-classes': { title: "What You Need to Know About ASHRAE's Fifth Edition of Thermal Guidelines", publisher: 'Upsite Technologies', url: 'https://www.upsite.com/blog/what-you-need-to-know-about-ashraes-fifth-edition-of-thermal-guidelines/' },
  'introl-wue': { title: 'Water Usage Efficiency: AI Data Center Cooling Without Crisis', publisher: 'Introl', url: 'https://introl.com/blog/water-usage-efficiency-wue-ai-data-center-cooling-guide-2025' },
  'nrel-water-electricity': { title: 'A review of operational water consumption and withdrawal factors for electricity generating technologies', publisher: 'NREL', url: 'https://docs.nrel.gov/docs/fy11osti/50900.pdf' },
  'vertiv-coolchip-cdu': { title: 'Vertiv CoolChip CDU', publisher: 'Vertiv', url: 'https://www.vertiv.com/en-us/products-catalog/thermal-management/high-density-solutions/vertiv-coolchip-cdu/' },
  'motivair-cdu-brochure': { title: 'CDU 2025 product brochure', publisher: 'Motivair (Schneider Electric)', url: 'https://www.motivaircorp.com/uploads/files/brochures/CDU%202025%20Motivair%20by%20SE_Updated_9_26_25.pdf' },
  'fortum-finland-heat': { title: 'Fortum has started heat production at two large data centre sites in Finland', publisher: 'Fortum', url: 'https://www.fortum.com/en/media/2026/05/fortum-has-started-heat-production-two-large-data-centre-sites-finland' },
  'munters-odense': { title: 'Harnessing heat from Odense data center for reuse in district heating', publisher: 'Munters', url: 'https://www.munters.com/en-us/knowledge-bank/case-studies/casestudy-13666/' },
  'stockholm-data-parks': { title: 'Stockholm Data Parks', publisher: 'Stockholm Exergi / City of Stockholm', url: 'https://stockholmdataparks.com/' },
  'microsoft-zero-water': { title: 'Sustainable by design: next-generation datacenters consume zero water for cooling', publisher: 'Microsoft', url: 'https://www.microsoft.com/en-us/microsoft-cloud/blog/2024/12/09/sustainable-by-design-next-generation-datacenters-consume-zero-water-for-cooling/' },
  'alliance-chemical-gpu-thermal': { title: 'GPU Thermal Density & Coolant Flow Specs: B200, GB200, MI300', publisher: 'Alliance Chemical', url: 'https://alliancechemical.com/blogs/articles/gpu-thermal-density-b200-gb200-coolant-flow-specs' },

  // UPS, PUE
  'eaton-9395xr-ups': { title: '9395XR UPS', publisher: 'Eaton', url: 'https://www.eaton.com/us/en-us/catalog/backup-power-ups-surge-it-power-distribution/eaton-9395xr-ups.html' },
  'google-pue': { title: 'Efficiency — Google Data Centers', publisher: 'Google', url: 'https://datacenters.google/efficiency/' },

  // GB200 / GB300 / 800 V DC rack platform
  'nvidia-gb200-nvl72': { title: 'GB200 NVL72', publisher: 'NVIDIA', url: 'https://www.nvidia.com/en-us/data-center/gb200-nvl72/' },
  'nvidia-gb200-ocp': { title: 'NVIDIA Contributes GB200 NVL72 Designs to Open Compute Project', publisher: 'NVIDIA', url: 'https://developer.nvidia.com/blog/nvidia-contributes-nvidia-gb200-nvl72-designs-to-open-compute-project/' },
  'nvidia-gb300-power': { title: 'How New GB300 NVL72 Features Provide Steady Power for AI', publisher: 'NVIDIA', url: 'https://developer.nvidia.com/blog/how-new-gb300-nvl72-features-provide-steady-power-for-ai/' },
  'nvidia-gb300-nvl72': { title: 'GB300 NVL72', publisher: 'NVIDIA', url: 'https://www.nvidia.com/en-us/data-center/gb300-nvl72/' },
  'nvidia-800v-hvdc': { title: 'NVIDIA 800 V HVDC Architecture Will Power the Next Generation of AI Factories', publisher: 'NVIDIA', url: 'https://developer.nvidia.com/blog/nvidia-800-v-hvdc-architecture-will-power-the-next-generation-of-ai-factories/' },
  'hpe-gb200-quickspecs': { title: 'NVIDIA GB200 NVL72 by HPE, QuickSpecs', publisher: 'HPE', url: 'https://www.hpe.com/us/en/collaterals/collateral.a50009224enw.html' },
  'navitas-800vdc': { title: "Navitas Supports 800 VDC Power Architecture for NVIDIA's Next-Generation AI Factory Computing Platforms", publisher: 'Navitas Semiconductor', url: 'https://navitassemi.com/navitas-supports-800-vdc-power-architecture-for-nvidias-next-generation-ai-factory-computing-platforms/' },
  'liteon-gb200-power-system': { title: 'NVIDIA GB200 Blackwell power system', publisher: 'LITE-ON', url: 'https://www.liteon.com/en/news/press-center/content/nvidia-gb200-blackwell-power-system' },
  'nvidia-nvl72-reference-arch': { title: 'NVL72 AI Factory reference architecture, System Hardware & Components', publisher: 'NVIDIA', url: 'https://docs.nvidia.com/enterprise-reference-architectures/nvl72-ai-factory/latest/components.html' },
  'nvidia-dgx-gb200-hardware': { title: 'DGX GB Rack Scale Systems User Guide, Hardware', publisher: 'NVIDIA', url: 'https://docs.nvidia.com/dgx/dgxgb200-user-guide/hardware.html' },
  'servethehome-dgx-gb200': { title: 'This is the NVIDIA DGX GB200 NVL72', publisher: 'ServeTheHome', url: 'https://www.servethehome.com/this-is-the-nvidia-dgx-gb200-nvl72/' },
  'naddod-gb200-interconnect': { title: 'NVIDIA GB200 Interconnect Architecture Analysis: NVLink, InfiniBand and Future Trends', publisher: 'NADDOD', url: 'https://www.naddod.com/blog/nvidia-gb200-interconnect-architecture-analysis-nvlink-infiniband-and-future-trends' },
  'amphenol-paladin-hd': { title: 'Paladin HD 224Gb/s Backplane Interconnect System', publisher: 'Amphenol', url: 'https://www.amphenol-cs.com/product-series/paladin-hd.html' },
  'semianalysis-nvl72-optics': { title: "NVIDIA's Optical Boogeyman: NVL72, InfiniBand", publisher: 'SemiAnalysis', url: 'https://newsletter.semianalysis.com/p/nvidias-optical-boogeyman-nvl72-infiniband' },
  'semianalysis-gb200-nvl72-specs': { title: 'NVIDIA GB200 NVL72 Specs, Pricing & AI Inference Benchmarks', publisher: 'SemiAnalysis / InferenceX', url: 'https://inferencex.semianalysis.com/chips/gb200-nvl72' },

  // H100 / DGX H100
  'nvidia-h100-datasheet': { title: 'H100 Tensor Core GPU datasheet', publisher: 'NVIDIA', url: 'https://resources.nvidia.com/en-us-gpu-resources/h100-datasheet-24306' },
  'nvidia-dgx-h100': { title: 'DGX H100 product page', publisher: 'NVIDIA', url: 'https://www.nvidia.com/en-eu/data-center/dgx-h100/' },
  'fs-com-dgx-h100': { title: 'Introduction to NVIDIA DGX H100', publisher: 'FS.com', url: 'https://www.fs.com/blog/introduction-to-nvidia-dgx-h100-3856.html' },

  // networking, optics, fiber
  'nvidia-xdr-switch-specs': { title: 'Quantum-X800 XDR switch systems, specifications', publisher: 'NVIDIA', url: 'https://networking-docs.nvidia.com/xdrswitcheshw/specifications' },
  'nvidia-sn5000-specs': { title: 'SN5000 switch systems, specifications', publisher: 'NVIDIA', url: 'https://networking-docs.nvidia.com/sn5000hw/specifications' },
  'nvidia-800g-dr8-datasheet': { title: '800Gb/s Twin-Port OSFP 2x400Gb/s Single-Mode DR8 datasheet', publisher: 'NVIDIA', url: 'https://docs.nvidia.com/nvidia-mms4x00-nm-800gbps-twin-port-osfp-2x400gb-s-single-mode-dr8-500m-12-07-2023.pdf' },
  'nvidia-connectx8-datasheet': { title: 'ConnectX-8 SuperNIC datasheet', publisher: 'NVIDIA', url: 'https://resources.nvidia.com/en-us-accelerated-networking-resource-library/connectx-datasheet-c' },
  'nvidia-spectrum-x-cpo': { title: 'NVIDIA Spectrum-X co-packaged optics networking switches for AI factories', publisher: 'NVIDIA', url: 'https://nvidianews.nvidia.com/news/nvidia-spectrum-x-co-packaged-optics-networking-switches-ai-factories' },
  'broadcom-davisson-cpo': { title: 'Broadcom Davisson co-packaged optics announcement', publisher: 'Broadcom', url: 'https://www.broadcom.com/company/news/product-releases/63626' },
  'nvidia-spectrum-xgs': { title: 'NVIDIA Introduces Spectrum-XGS Ethernet to Connect Distributed Data Centers', publisher: 'NVIDIA', url: 'https://nvidianews.nvidia.com/news/nvidia-introduces-spectrum-xgs-ethernet-to-connect-distributed-data-centers-into-giga-scale-ai-super-factories' },
  'microsoft-ai-wan': { title: 'From Wisconsin to Atlanta: Microsoft connects datacenters to build its first AI superfactory', publisher: 'Microsoft', url: 'https://news.microsoft.com/source/features/ai/from-wisconsin-to-atlanta-microsoft-connects-datacenters-to-build-its-first-ai-superfactory/' },
  'datacenterfrontier-fairwater': { title: "Microsoft's Fairwater Atlanta and the Rise of the Distributed AI Supercomputer", publisher: 'Data Center Frontier', url: 'https://www.datacenterfrontier.com/machine-learning/article/55330039/microsofts-fairwater-atlanta-and-the-rise-of-the-distributed-ai-supercomputer' },
  'google-cloud-networking-ai': { title: 'Data center and global networks built for the AI era', publisher: 'Google Cloud', url: 'https://cloud.google.com/blog/products/networking/data-center-and-global-networks-built-for-ai-era' },
  'deepmind-decoupled-diloco': { title: 'Decoupled DiLoCo', publisher: 'Google DeepMind', url: 'https://deepmind.google/blog/decoupled-diloco/' },
  'ciena-wavelogic6': { title: 'Ciena Unveils WaveLogic 6', publisher: 'Ciena', url: 'https://www.ciena.com/about/newsroom/press-releases/ciena-unveils-wavelogic-6' },
  'corning-edge8': { title: 'EDGE8 Housings', publisher: 'Corning', url: 'https://ecatalog.corning.com/optical-communications/US/en/Fiber-Optic-Hardware/Housings/EDGE8%C2%AE-Housings/p/EDGE8-01U-SP' },
  'coherent-full-cband-pols': { title: 'ECOC: Coherent Extends Pluggable Line System Across Full C-Band', publisher: 'Converge Digest', url: 'https://convergedigest.com/coherent-full-c-band-pols-25-6tbps-ai-dci/' },
  'cisco-8800-routers': { title: '8800 Series Modular Routers data sheet', publisher: 'Cisco', url: 'https://www.cisco.com/c/en/us/products/collateral/routers/8000-series-routers/8800-series-modular-routers-ds.html' },
  'microsoft-hollow-core-fiber': { title: 'Microsoft Scales Up Hollow Core Fiber Production', publisher: 'Fiber Broadband Association', url: 'https://fiberbroadband.org/2026/04/02/microsoft-scales-up-hollow-core-fiber-production/' },
  'prysmian-flexribbon': { title: 'FlexRibbon whitepaper', publisher: 'Prysmian', url: 'https://www.prysmian.com/sites/default/files/business_markets/markets/downloads/datasheets/FlexRibbon-Whitepaper.pdf' },
  'google-ironwood-tpu': { title: 'Ironwood: the first Google TPU for the age of inference', publisher: 'Google Cloud', url: 'https://blog.google/products/google-cloud/ironwood-google-tpu-things-to-know/' },

  // board, chip, power delivery
  'semianalysis-blackwell-power-delivery': { title: 'Energizing AI: Power Delivery Competition Heats Up', publisher: 'SemiAnalysis', url: 'https://newsletter.semianalysis.com/p/energizing-ai-power-delivery-competition' },
  'arxiv-gpu-power-visibility': { title: 'Methodology for Fine-Grain GPU Power Visibility and Insights', publisher: 'arXiv', url: 'https://arxiv.org/html/2412.12426v1' },
  'nvidia-blackwell-ultra-blog': { title: 'Inside NVIDIA Blackwell Ultra: The Chip Powering the AI Factory Era', publisher: 'NVIDIA', url: 'https://developer.nvidia.com/blog/inside-nvidia-blackwell-ultra-the-chip-powering-the-ai-factory-era' },
  'wccftech-nv-hbi': { title: 'NVIDIA Deep-Dives Into Blackwell Infrastructure: NV-HBI Used to Fuse Two AI GPUs Together', publisher: 'WCCFTech', url: 'https://wccftech.com/nvidia-blackwell-ai-deep-dive-nv-hbi-fuse-two-ai-gpus-together-5th-gen-tensor-cores-5th-gen-nvlink-spectrum-x/' },
  'micron-hbm3e-brief': { title: 'HBM3E product brief', publisher: 'Micron', url: 'https://assets.micron.com/adobe/assets/urn:aaid:aem:b710d8f2-7f66-44c1-a234-456e2b986347/original/as/hbm3e-product-brief.pdf' },

  // tokens, training, carbon, models
  'samsi-words-to-watts': { title: 'From Words to Watts: Benchmarking the Energy Costs of Large Language Model Inference', publisher: 'Samsi et al., arXiv', url: 'https://arxiv.org/pdf/2310.03003' },
  'semianalysis-inferencemax': { title: 'InferenceMAX: Open Source Inference Benchmarking', publisher: 'SemiAnalysis', url: 'https://newsletter.semianalysis.com/p/inferencemax-open-source-inference' },
  'google-inference-impact': { title: 'Measuring the environmental impact of AI inference', publisher: 'Google Cloud', url: 'https://cloud.google.com/blog/products/infrastructure/measuring-the-environmental-impact-of-ai-inference/' },
  'google-inference-impact-paper': { title: 'Measuring the environmental impact of delivering AI at Google scale', publisher: 'Google, arXiv', url: 'https://arxiv.org/abs/2508.15734' },
  'meta-llama31-model-card': { title: 'Llama 3.1 model card', publisher: 'Meta', url: 'https://github.com/meta-llama/llama-models/blob/main/models/llama3_1/MODEL_CARD.md' },
  'meta-llama3-herd-parallelism': { title: 'The Llama 3 Herd of Models', publisher: 'Meta AI, arXiv', url: 'https://arxiv.org/pdf/2407.21783' },
  'deepseek-v3-technical-report': { title: 'DeepSeek-V3 Technical Report', publisher: 'DeepSeek-AI, arXiv', url: 'https://arxiv.org/pdf/2412.19437' },
  'nvidia-gb200-dynamo-moe': { title: 'How NVIDIA GB200 NVL72 and NVIDIA Dynamo Boost Inference Performance for MoE Models', publisher: 'NVIDIA', url: 'https://developer.nvidia.com/blog/how-nvidia-gb200-nvl72-and-nvidia-dynamo-boost-inference-performance-for-moe-models' },
  'epoch-chatgpt-energy': { title: 'How much energy does ChatGPT use?', publisher: 'Epoch AI', url: 'https://epoch.ai/gradient-updates/how-much-energy-does-chatgpt-use' },
  'nvidia-hgx-h100-pcf': { title: 'HGX H100 Product Carbon Footprint summary', publisher: 'NVIDIA', url: 'https://images.nvidia.com/aem-dam/Solutions/documents/HGX-H100-PCF-Summary.pdf' },
  // real sites and state carbon (research/scenario-sources.md, sections E and F)
  'dcd-fairwater-atlanta': { title: 'Microsoft launches Atlanta Fairwater AI data center: two stories, no UPS or gen-sets', publisher: 'Data Center Dynamics', url: 'https://www.datacenterdynamics.com/en/news/microsoft-launches-atlanta-fairwater-data-center-two-stories-no-ups-or-gen-sets/' },
  'microsoft-infinite-scale': { title: 'Infinite scale: The architecture behind the Azure AI superfactory', publisher: 'Microsoft', url: 'https://blogs.microsoft.com/blog/2025/11/12/infinite-scale-the-architecture-behind-the-azure-ai-superfactory/' },
  'dcd-fairwater-wisconsin': { title: 'Microsoft increases Wisconsin data center investment to $7.3bn', publisher: 'Data Center Dynamics', url: 'https://www.datacenterdynamics.com/en/news/microsoft-increases-wisconsin-data-center-investment-to-73bn-says-fairwater-site-will-be-worlds-most-powerful-data-center/' },
  'techtimes-fairwater-wisconsin': { title: 'Microsoft Opens Fairwater: Wisconsin AI Campus Runs as One Supercomputer via 800G Ethernet', publisher: 'TechTimes', url: 'https://www.techtimes.com/articles/319205/20260627/microsoft-opens-fairwater-wisconsin-ai-campus-runs-one-supercomputer-via-800g-ethernet.htm' },
  'meta-richland-parish': { title: 'The largest Meta data center yet brings big impact to Louisiana', publisher: 'Meta', url: 'https://datacenters.atmeta.com/richland-parish-data-center/' },
  'cnbc-meta-louisiana': { title: "Meta's Louisiana data center investment to reach $50 billion", publisher: 'CNBC', url: 'https://www.cnbc.com/2026/07/13/meta-louisiana-data-center-investment-reaches-50-billion-amid-ai-push.html' },
  'led-meta-louisiana': { title: 'Meta Commits More Than $50 Billion for North Louisiana Project', publisher: 'Louisiana Economic Development', url: 'https://www.opportunitylouisiana.gov/news/meta-commits-more-than-50-billion-for-north-louisiana-project-becoming-one-of-the-largest-data-centers-in-history' },
  'wikipedia-colossus': { title: 'Colossus (data center)', publisher: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Colossus_(data_center)' },
  'tomshardware-colossus': { title: "Musk's Colossus is fully operational with 200,000 GPUs", publisher: "Tom's Hardware", url: 'https://www.tomshardware.com/tech-industry/artificial-intelligence/musks-colossus-is-fully-operational-with-200-000-gpus-backed-by-tesla-batteries-phase-2-to-consume-300-mw-enough-to-power-300-000-homes' },
  'eia-state-texas': { title: 'Texas Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/texas/' },
  'eia-state-tennessee': { title: 'Tennessee Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/tennessee/' },
  'eia-state-georgia': { title: 'Georgia Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/georgia/' },
  'eia-state-wisconsin': { title: 'Wisconsin Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/wisconsin/' },
  'eia-state-louisiana': { title: 'Louisiana Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/louisiana/' },
  'eia-state-virginia': { title: 'Virginia Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/virginia/' },
  'eia-state-oregon': { title: 'Oregon Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/oregon/' },
  'eia-state-washington': { title: 'Washington Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/washington/' },
  'eia-state-arizona': { title: 'Arizona Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/arizona/' },
  'eia-state-ohio': { title: 'Ohio Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/ohio/' },
  'eia-state-iowa': { title: 'Iowa Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/iowa/' },
  'eia-state-newyork': { title: 'New York Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/newyork/' },
};

// PART_SOURCES: which sources back the specs on each card. Key = '<layer>:<sceneId>:<partId>',
// layer is 'power' | 'data' | 'heat'. Empty array = the card is estimate-only, no source to cite.
export const PART_SOURCES = {
  // ---- power ----
  'power:across:carbon': ['eia-state-texas', 'eia-state-tennessee', 'eia-state-georgia', 'eia-state-wisconsin', 'eia-state-louisiana', 'eia-state-washington', 'eia-co2-per-kwh'],
  'power:across:site-abilene': ['epoch-dc-abilene', 'epoch-stargate-abilene'],
  'power:across:site-colossus1': ['compute-atlas-colossus', 'epoch-dc-colossus2', 'epoch-largest-dc', 'wikipedia-colossus', 'tomshardware-colossus', 'semianalysis-xai-colossus2'],
  'power:across:site-fairwater-atl': ['epoch-dc-fairwater-atl', 'microsoft-infinite-scale', 'dcd-fairwater-atlanta', 'datacenterfrontier-fairwater'],
  'power:across:site-fairwater-wi': ['epoch-dc-fairwater-wi', 'dcd-fairwater-wisconsin', 'techtimes-fairwater-wisconsin'],
  'power:across:site-hyperion': ['epoch-dc-hyperion', 'meta-richland-parish', 'cnbc-meta-louisiana', 'led-meta-louisiana'],
  'power:across:grid': ['ieee-spectrum-hyperion', 'epoch-stargate-abilene'],
  'power:across:plants': ['eia-td-losses'],
  'power:across:home': [],

  'power:campus:line': ['eia-td-losses', 'epoch-stargate-abilene'],
  'power:campus:substation': [],
  'power:campus:mpt': ['pa-transformer-345kv', 'transformer-lead-times'],
  'power:campus:ehouse': ['mv-distribution-atk'],
  'power:campus:gensets': ['cummins-dqkan-genset'],
  'power:campus:fuel': ['cummins-dqkan-genset'],
  'power:campus:bess': ['nvidia-bess-blog', 'dcd-xai-colossus-memphis'],
  'power:campus:unitsubs': ['doe-transformer-efficiency'],
  'power:campus:hall': [],
  'power:campus:drycoolers': ['ashrae-liquid-cooling-classes', 'introl-wue'],
  'power:campus:chillers': [],
  'power:campus:towers': ['introl-wue', 'nrel-water-electricity'],
  'power:campus:fiber': ['zayo-route-diversity'],

  'power:hall:unitsub': ['doe-transformer-efficiency'],
  'power:hall:swgr': [],
  'power:hall:sst': ['navitas-800vdc', 'nvidia-800v-hvdc'],
  'power:hall:ups': ['eaton-9395xr-ups'],
  'power:hall:batt': [],
  'power:hall:busway': ['lv-distribution-busway', 'nvidia-800v-hvdc'],
  'power:hall:racks': ['nvidia-gb200-nvl72', 'hpe-gb200-quickspecs', 'nvidia-dgx-h100'],
  'power:hall:containment': [],
  'power:hall:inrow': [],
  'power:hall:cdu': ['vertiv-coolchip-cdu', 'motivair-cdu-brochure'],
  'power:hall:fwater': [],
  'power:hall:fanwall': [],
  'power:hall:network': [],

  'power:rack:feed': [],
  'power:rack:shelves': ['navitas-800vdc', 'nvidia-gb200-ocp', 'liteon-gb200-power-system'],
  'power:rack:busbar': ['nvidia-gb200-ocp', 'nvidia-800v-hvdc'],
  'power:rack:compute': ['nvidia-gb200-nvl72'],
  'power:rack:nvswitch': ['nvidia-nvl72-reference-arch'],
  'power:rack:spine': ['nvidia-gb200-ocp', 'servethehome-dgx-gb200'],
  'power:rack:manifold': [],
  'power:rack:pdu': [],
  'power:rack:servers': ['nvidia-dgx-h100', 'nvidia-h100-datasheet'],
  'power:rack:psus': ['fs-com-dgx-h100'],
  'power:rack:cabling': [],
  'power:rack:mgmt': [],

  'power:tray:clip': [],
  'power:tray:ibc': ['semianalysis-blackwell-power-delivery'],
  'power:tray:vrm': ['semianalysis-blackwell-power-delivery'],
  'power:tray:gpu': ['nvidia-gb200-nvl72', 'nvidia-gb300-nvl72', 'nvidia-h100-datasheet'],
  'power:tray:grace': ['nvidia-gb200-nvl72'],
  'power:tray:lpddr': ['nvidia-gb200-nvl72'],
  'power:tray:coldplates': [],
  'power:tray:nic': ['nvidia-connectx8-datasheet', 'nvidia-gb300-nvl72'],
  'power:tray:nvconn': ['nvidia-gb200-nvl72'],
  'power:tray:psu': ['fs-com-dgx-h100'],
  'power:tray:cpu': [],
  'power:tray:heatsinks': [],
  'power:tray:nvswitch': ['nvidia-h100-datasheet'],

  'power:chip:balls': ['semianalysis-blackwell-power-delivery'],
  'power:chip:interposer': ['nvidia-blackwell-ultra-blog', 'wccftech-nv-hbi'],
  'power:chip:dies': ['nvidia-blackwell-ultra-blog', 'wccftech-nv-hbi'],
  'power:chip:hbm': ['micron-hbm3e-brief', 'arxiv-gpu-power-visibility'],
  'power:chip:tokens': ['google-inference-impact', 'samsi-words-to-watts'],

  // ---- data ----
  'data:across:dci': ['ciena-wavelogic6'],
  'data:across:ila': [],
  'data:across:route': ['microsoft-hollow-core-fiber', 'coherent-full-cband-pols'],
  'data:across:remote': ['microsoft-ai-wan', 'nvidia-spectrum-xgs', 'deepmind-decoupled-diloco'],
  'data:across:home': [],

  'data:campus:fiber': ['zayo-route-diversity'],
  'data:campus:dci': ['ciena-wavelogic6'],
  'data:campus:interhall': [],
  'data:campus:ductbank': ['prysmian-flexribbon'],
  'data:campus:hall': [],
  'data:campus:longhaul': [],

  'data:hall:odf': ['corning-edge8'],
  'data:hall:crosshall': [],
  'data:hall:pp': ['meta-llama3-herd-parallelism'],
  'data:hall:dp': ['meta-llama3-herd-parallelism', 'deepseek-v3-technical-report'],
  'data:hall:uplinks': [],
  'data:hall:leaf': [],
  'data:hall:spine': ['nvidia-xdr-switch-specs'],
  'data:hall:runways': [],
  'data:hall:optics': ['nvidia-800g-dr8-datasheet'],
  'data:hall:cpo': ['nvidia-spectrum-x-cpo', 'broadcom-davisson-cpo'],
  'data:hall:racks': ['nvidia-gb200-nvl72'],

  'data:rack:tp': ['meta-llama3-herd-parallelism'],
  'data:rack:nvswitch': ['nvidia-nvl72-reference-arch'],
  'data:rack:spine': ['nvidia-gb200-ocp', 'servethehome-dgx-gb200'],
  'data:rack:optical': ['google-ironwood-tpu'],
  'data:rack:uplinks': ['nvidia-h100-datasheet'],
  'data:rack:compute': [],
  'data:rack:mgmt': [],
  'data:rack:servers': ['nvidia-h100-datasheet'],

  'data:tray:nvconn': ['nvidia-gb200-nvl72'],
  'data:tray:c2c': ['nvidia-gb200-nvl72', 'naddod-gb200-interconnect'],
  'data:tray:cx': ['nvidia-connectx8-datasheet', 'fs-com-dgx-h100'],
  'data:tray:osfp': ['nvidia-800g-dr8-datasheet'],
  'data:tray:dpu': ['nvidia-dgx-gb200-hardware'],
  'data:tray:gpu': [],
  'data:tray:nvswitch': ['nvidia-h100-datasheet'],
  'data:tray:pcie': [],

  'data:chip:hbm': ['micron-hbm3e-brief'],
  'data:chip:hbi': ['wccftech-nv-hbi'],
  'data:chip:nvphy': [],
  'data:chip:cpo': ['nvidia-spectrum-x-cpo'],
  'data:chip:tokens': [],

  // ---- heat ----
  'heat:across:climate': [],
  'heat:across:home': [],

  'heat:campus:drycoolers': ['ashrae-liquid-cooling-classes', 'alliance-chemical-gpu-thermal'],
  'heat:campus:chillers': [],
  'heat:campus:towers': ['introl-wue', 'nrel-water-electricity'],
  'heat:campus:plume': [],
  'heat:campus:reuse': ['fortum-finland-heat', 'munters-odense', 'stockholm-data-parks'],

  'heat:hall:inrow': [],
  'heat:hall:cdu': ['vertiv-coolchip-cdu'],
  'heat:hall:fwater': [],
  'heat:hall:hotaisle': [],
  'heat:hall:fanwall': [],
  'heat:hall:riser': [],

  'heat:rack:manifold': ['alliance-chemical-gpu-thermal'],
  'heat:rack:rearair': [],
  'heat:rack:compute': [],
  'heat:rack:front': [],
  'heat:rack:servers': [],

  'heat:tray:coldplates': [],
  'heat:tray:gpuheat': [],
  'heat:tray:fans': [],
  'heat:tray:qd': [],
  'heat:tray:heatsinks': [],

  'heat:chip:junction': [],
  'heat:chip:flux': ['alliance-chemical-gpu-thermal'],
  'heat:chip:tim': [],
  'heat:chip:hbm': ['micron-hbm3e-brief'],
};

// LEDGER_SOURCES: [labelPrefix, sourceIds] pairs, matched with row.label.startsWith(prefix).
export const LEDGER_SOURCES = [
  ['Main power transformers', ['pa-transformer-345kv', 'transformer-lead-times']],
  ['Campus cables & switchgear', []],
  ['Unit substations', ['doe-transformer-efficiency']],
  ['Solid-state transformers', ['navitas-800vdc', 'nvidia-800v-hvdc']],
  ['800 V DC bus & batteries', ['nvidia-800v-hvdc']],
  ['UPS, double conversion', ['eaton-9395xr-ups']],
  ['Busway & whips', ['lv-distribution-busway', 'nvidia-800v-hvdc']],
  ['Cooling:', ['ashrae-liquid-cooling-classes', 'introl-wue']],
  ['Lighting, controls, offices', []],
  ['Scale-out switches', ['nvidia-xdr-switch-specs']],
  ['Optical transceivers', ['nvidia-800g-dr8-datasheet']],
  ['In-rack DC-DC', ['navitas-800vdc']],
  ['Server power supplies', ['fs-com-dgx-h100']],
  ['Rack power shelves', ['liteon-gb200-power-system', 'nvidia-gb200-ocp']],
  ['Server power cabling', []],
  ['Busbar', ['nvidia-gb200-ocp']],
  ['NVSwitch chips', ['nvidia-h100-datasheet']],
  ['NVLink switch trays', ['nvidia-nvl72-reference-arch']],
  ['x86 CPUs', []],
  ['Grace CPUs', ['nvidia-gb200-nvl72']],
  ['Vera CPUs', []],
  ['NICs & DPUs', ['fs-com-dgx-h100']],
  ['SuperNICs & DPUs', ['nvidia-connectx8-datasheet']],
  ['SSDs, fans, management', []],
  ['Bus converters', ['semianalysis-blackwell-power-delivery']],
  ['Voltage regulators', ['semianalysis-blackwell-power-delivery']],
  ['HBM', ['micron-hbm3e-brief']],
];

// EST_NOTES: one sentence on how an estimate was derived, only where data.js's own formula
// or the research notes actually say so.
export const EST_NOTES = {
  'power:campus:line': 'Per-phase current from campus MW ÷ (√3 × 345 kV × 0.95 assumed power factor).',
  'power:campus:fuel': 'Tanker count from the 48-hour fuel volume ÷ 30,000 L per truckload.',
  'power:hall:unitsub': 'Secondary current from 2.5 MVA ÷ (√3 × 480 V × 0.95 assumed power factor).',
  'power:hall:busway': 'Per-rack current from rack kW ÷ (√3 × 415 V × 0.95 assumed power factor).',
  'power:hall:racks': 'Liquid/air kW split from the rack total × HPE\'s published liquid share for this rack.',
  'power:rack:busbar': 'Busbar current from the rack DC bus power ÷ 50 V.',
  'power:chip:balls': 'Core current from GPU power (minus HBM share) ÷ 0.8 V assumed core voltage.',
  'power:tray:vrm': 'Core current from GPU power (minus HBM share) ÷ 0.8 V assumed core voltage.',
  'heat:chip:flux': 'Average flux from GPU power (minus HBM share) ÷ die area; hot spots run well above this average.',
  'heat:tray:fans': 'Airflow from rack heat, air density and specific heat at a 15 °C rise (Q = ṁ·cp·ΔT).',
};
