// Sources for the "source popovers" on basis chips. SOURCES holds the reusable citations;
// PART_SOURCES and LEDGER_SOURCES point each card / ledger row at the citations behind it;
// EST_NOTES explains, in one sentence, how a handful of estimates were derived. Every URL
// here appears verbatim in research/*.md or in the footer of index.html — never invented.

export const SOURCES = {
  // grid, campus, transformers, generators
  'eia-td-losses': { title: 'How much electricity is lost in electricity transmission and distribution', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/tools/faqs/faq.php?id=105&t=5' },
  'eia-co2-per-kwh': { title: 'How much carbon dioxide is produced per kilowatthour of U.S. electricity generation', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/tools/faqs/faq.php?id=74&t=11' },
  'epoch-stargate-abilene': { title: 'OpenAI Stargate: where the US sites stand', publisher: 'Epoch AI', url: 'https://epoch.ai/publications/openai-stargate-where-the-us-sites-stand' },
  'epoch-dc-abilene': { title: 'OpenAI Stargate Abilene, Frontier Data Centers (updated 09/24/2026)', publisher: 'Epoch AI', url: 'https://epoch.ai/data/ai-data-centers/directory/openai-stargate-abilene' },
  'epoch-dc-colossus2': { title: 'xAI Colossus 2, Frontier Data Centers (updated 09/24/2026)', publisher: 'Epoch AI', url: 'https://epoch.ai/data/ai-data-centers/directory/colossus-2' },
  'epoch-dc-fairwater-atl': { title: 'Microsoft Fairwater Atlanta, Frontier Data Centers (updated 09/24/2026)', publisher: 'Epoch AI', url: 'https://epoch.ai/data/ai-data-centers/directory/microsoft-fairwater-atlanta' },
  'epoch-dc-fairwater-wi': { title: 'Microsoft Fairwater Wisconsin, Frontier Data Centers (updated 09/24/2026)', publisher: 'Epoch AI', url: 'https://epoch.ai/data/ai-data-centers/directory/microsoft-fairwater-wisconsin' },
  'epoch-dc-hyperion': { title: 'Meta Hyperion, Frontier Data Centers', publisher: 'Epoch AI', url: 'https://epoch.ai/data/ai-data-centers/directory/meta-hyperion' },
  'epoch-largest-dc': { title: 'Largest AI data centers by power capacity (updated 09/24/2026)', publisher: 'Epoch AI', url: 'https://epoch.ai/graphs/largest-ai-data-centers-by-power-capacity' },
  'epoch-dc-new-carlisle': { title: "Anthropic-Amazon New Carlisle, Frontier Data Centers (updated 09/24/2026)", publisher: "Epoch AI", url: "https://epoch.ai/data/ai-data-centers/directory/anthropic-amazon-new-carlisle" },
  'eia-state-indiana': { title: "Indiana Electricity Profile 2024", publisher: "U.S. Energy Information Administration", url: "https://www.eia.gov/electricity/state/indiana/" },
  'measuredai-new-carlisle': { title: "AWS New Carlisle Data Center Campus: Project Rainier — Where Anthropic Trains Claude", publisher: "Measured AI (Substack)", url: "https://measuredai.substack.com/p/aws-new-carlisle-data-center-campus" },
  'compute-atlas-rainier': { title: "Amazon Project Rainier — Amazon Web Services data center in New Carlisle, IN", publisher: "Compute Atlas", url: "https://www.compute-atlas.com/facilities/amazon-project-rainier-new-carlisle-in" },
  'blackridge-rainier': { title: "AWS Project Rainier, Indiana: Latest Updates (2026)", publisher: "BlackRidge Research", url: "https://www.blackridgeresearch.com/project-profiles/aws-project-rainier-new-carlisle-indiana-usa-data-center-supercluster-cost-contractors-timeline-latest-updates" },
  'epoch-dc-prometheus': { title: "Meta Prometheus", publisher: "Epoch AI", url: "https://epoch.ai/data/ai-data-centers/directory/meta-prometheus" },
  'epoch-satellite-prometheus': { title: "Meta Prometheus — Frontier Data Centers Satellite Explorer", publisher: "Epoch AI", url: "https://epoch.ai/data/data-centers/satellite-explorer/MetaPrometheusNewAlbanyOhio" },
  'mlq-meta-gas-tents': { title: "Meta Deploys Tent-Based Data Centers in Ohio and Tennessee, Backed by 400MW of Off-Grid Gas Power", publisher: "MLQ.ai", url: "https://mlq.ai/news/meta-deploys-tent-based-data-centers-in-ohio-and-tennessee-backed-by-400mw-of-off-grid-gas-power/" },
  'measuredai-prometheus-primer': { title: "Meta's Prometheus and Google's Central Ohio Cluster: An AI Data Center Primer", publisher: "Measured AI (Substack)", url: "https://measuredai.substack.com/p/meta-prometheus-google-ohio" },
  'techcrunch-meta-tents': { title: "Meta steals a tactic from Tesla and builds data centers in tents", publisher: "TechCrunch", url: "https://techcrunch.com/2026/06/04/meta-steals-a-tactic-from-tesla-and-builds-data-centers-in-tents/" },
  'nvidia-sn5000-datasheet': { title: "Spectrum SN5000 Ethernet switch series data sheet", publisher: "NVIDIA", url: "https://nvdam.widen.net/s/mmvbnpk8qk/networking-ethernet-switches-sn5000-datasheet-us" },
  'nvidia-quantum-x800-switches': { title: "Quantum-X800 XDR InfiniBand switches (Q3400)", publisher: "NVIDIA", url: "https://networking-docs.nvidia.com/xdrswitcheshw/introduction" },
  'nvidia-rubin-platform': { title: "Rubin platform: the chips of the next AI supercomputer", publisher: "NVIDIA", url: "https://nvidianews.nvidia.com/news/rubin-platform-ai-supercomputer" },
  'nvidia-dpu-supernic': { title: "BlueField DPUs and ConnectX SuperNICs", publisher: "NVIDIA", url: "https://www.nvidia.com/en-us/networking/products/data-processing-unit/" },
  'nvidia-bluefield-datasheet': { title: "BlueField-3 DPU data sheet", publisher: "NVIDIA", url: "https://resources.nvidia.com/en-us-accelerated-networking-resource-library/datasheet-nvidia-bluefield" },
  'nvidia-bluefield4-datasheet': { title: "BlueField-4 DPU data sheet", publisher: "NVIDIA", url: "https://resources.nvidia.com/en-us-accelerated-networking-resource-library/bluefield-4-dpu-datasheet" },
  'cummins-qsk78': { title: "QSK78 diesel generator set", publisher: "Cummins", url: "https://www.cummins.com/en-na/generators/products/qsk78" },
  'cat-c175-16': { title: "C175-16 diesel generator set", publisher: "Caterpillar", url: "https://www.cat.com/en_US/products/new/power-systems/electric-power/diesel-generator-sets/1000028916.html" },
  'delta-ocp-800vdc': { title: "Delta demonstrates HVDC power, cooling and networking at the OCP Global Summit", publisher: "Delta Electronics", url: "https://www.deltapowersolutions.com/en/mcis/news-2025-delta-demonstrate-hvdc-power-cooling-networking-to-drive-ai-data-center-evolution-at-ocp-global-summit.php" },
  'infineon-solaredge-sst': { title: "Infineon and SolarEdge partner on high-efficiency power for AI data centers", publisher: "Power Electronics News", url: "https://www.powerelectronicsnews.com/infineon-and-solaredge-partner-to-advance-high-efficiency-power-infrastructure-for-next-gen-ai-data-centers/" },
  'liteon-gtc-2026': { title: "LITEON 800 VDC power rack and 110 kW power shelf, GTC 2026", publisher: "LITEON", url: "https://www.liteon.com/en/news/press-center/content/liteon-nvidia-gtc-2026" },
  'skhynix-hbm4': { title: "SK hynix completes the first HBM4 development and readies mass production", publisher: "SK hynix", url: "https://news.skhynix.com/en/sk-hynix-completes-worlds-first-hbm4-development-and-readies-mass-production/" },
  'micron-hbm4': { title: "HBM4", publisher: "Micron", url: "https://www.micron.com/products/memory/hbm/hbm4" },
  'samsung-hbm4': { title: "Samsung ships the first commercial HBM4", publisher: "Samsung Semiconductor", url: "https://semiconductor.samsung.com/news-events/news/samsung-ships-industry-first-commercial-hbm4-with-ultimate-performance-for-ai-computing/" },
  'innolight-1p6t': { title: "1.6T OSFP224 transceivers", publisher: "InnoLight", url: "https://www.innolight.com/data-center-networking/1.6t-osfp224" },
  'coherent-1p6t-dr8': { title: "1.6T DR8 OSFP transceiver", publisher: "Coherent", url: "https://www.coherent.com/networking/transceivers/datacom/FTCF2519E3PCA" },
  'evapco-apex': { title: "APEX dry cooler", publisher: "EVAPCO", url: "https://www.evapco.com/apex" },
  'bac-data-centers': { title: "Data center cooling, including TrilliumSeries dry coolers", publisher: "Baltimore Aircoil Company", url: "https://baltimoreaircoil.com/data-centers" },
  'schneider-uniflair': { title: "Uniflair cooling", publisher: "Schneider Electric", url: "https://www.se.com/us/en/work/products/master-ranges/uniflair/" },
  'marvell-alaska-a-aec': { title: "Marvell extends connectivity leadership with the first 1.6T PAM4 DSP for active electrical cables", publisher: "Marvell, via PR Newswire", url: "https://www.prnewswire.com/news-releases/marvell-extends-connectivity-leadership-with-industrys-first-1-6t-pam4-dsp-for-active-electrical-cables-302184240.html" },
  'credo-hiwire-800g-aec': { title: "Credo HiWire 800G AEC cables", publisher: "Open Compute Project marketplace", url: "https://www.opencompute.org/products/522/credos-hiwire-800g-aec-cables-straight" },
  'astera-taurus-scm': { title: "Taurus Ethernet smart cable modules", publisher: "Astera Labs", url: "https://www.asteralabs.com/products/taurus-ethernet-smart-cable-modules/" },
  'marvell-ara-1p6t-portfolio': { title: "Marvell ushers in the 1.6T era with an expanded optical DSP portfolio", publisher: "Marvell", url: "https://investor.marvell.com/news-events/press-releases/detail/1013/marvell-ushers-in-the-1-6t-era-with-expanded-optical-dsp-platform-portfolio-redefining-ai-data-center-end-to-end-connectivity" },
  'credo-bluebird-dsp': { title: "Bluebird 1.6T optical DSP", publisher: "Credo", url: "https://credosemi.com/products/optical-dsp/bluebird/" },
  'marvell-colorz-800': { title: "Marvell launches the first 800G ZR/ZR+ modules for data center interconnects", publisher: "Marvell, via PR Newswire", url: "https://www.prnewswire.com/news-releases/marvell-launches-industrys-first-800g-zrzr-modules-for-data-center-interconnects-301907609.html" },
  'ciena-wavelogic6-nano': { title: "WaveLogic 6 Nano: 800G pluggables and 1.6T Coherent-Lite", publisher: "Ciena", url: "https://www.ciena.com/insights/infobriefs/wavelogic-6-nano-1-6t-coherent-lite-pluggable-transceiver" },
  'broadcom-tomahawk6': { title: "Broadcom now shipping the first 102.4 Tb/s switch in production volume", publisher: "Broadcom", url: "https://www.broadcom.com/company/news/product-releases/64031" },
  'marvell-teralynx10': { title: "Marvell Teralynx 10 51.2T Ethernet switch enters volume production for AI cloud deployments", publisher: "Marvell", url: "https://www.marvell.com/company/newsroom/marvell-teralynx-10-51-2t-ethernet-switch-enters-volume-production-for-global-ai-cloud-deployments.html" },
  'compute-atlas-colossus': { title: 'xAI Colossus, Memphis, TN (checked 09/23/2026)', publisher: 'Compute Atlas', url: 'https://www.compute-atlas.com/facilities/xai-colossus-memphis-tn' },
  'ieee-spectrum-hyperion': { title: '5GW Data Center Buildout Requires Novel Engineering', publisher: 'IEEE Spectrum', url: 'https://spectrum.ieee.org/5gw-data-center' },
  'dcd-xai-colossus-memphis': { title: "Fury from campaigners as Elon Musk's xAI gets 150MW for Colossus supercomputer in Memphis", publisher: 'Data Center Dynamics', url: 'https://www.datacenterdynamics.com/en/news/xai-colossus-memphis-power-tva/' },
  'semianalysis-xai-colossus2': { title: "xAI's Colossus 2 — First Gigawatt Datacenter", publisher: 'SemiAnalysis', url: 'https://newsletter.semianalysis.com/p/xais-colossus-2-first-gigawatt-datacenter' },
  'pa-transformer-345kv': { title: '345 kV Power Transformer Projects', publisher: 'PA Transformer', url: 'https://www.patransformer.com/power-transformer-projects/power-transformer-345-kv/' },
  'transformer-lead-times': { title: 'HV Transformer Lead Times 2026: EU vs US', publisher: 'GridReadiness', url: 'https://www.gridreadiness.com/blog/power-transformer-lead-times-ai-data-center-2026.html' },
  'doe-transformer-efficiency': { title: 'Energy Conservation Standards for Distribution Transformers, final rule', publisher: 'U.S. Department of Energy', url: 'https://www1.eere.energy.gov/buildings/appliance_standards/pdfs/dt_final_rule.pdf' },
  'mv-distribution-atk': { title: 'Medium-Voltage Distribution for Data Center Campuses in 2026', publisher: 'ATK Energy Group', url: 'https://atkenergygroup.com/blog/medium-voltage-distribution-data-center-campuses/' },
  'cummins-dqkan-genset': { title: 'DQKAN 2.5 MW generator data sheet', publisher: 'Cummins', url: 'https://www.globalpwr.com/wp-content/uploads/cut-sheets/gps-cummins-2500-kw-dqkan-data-sheet.pdf' },
  'nvidia-bess-blog': { title: 'Designing Production-Ready Battery Energy Storage Systems for AI Factories', publisher: 'NVIDIA', url: 'https://developer.nvidia.com/blog/designing-production-ready-battery-energy-storage-systems-for-ai-factories' },
  'lv-distribution-busway': { title: 'LV Distribution: Busway, PDUs, RPPs & Rack Power', publisher: 'The Definitive Guide to AI Data Centers', url: 'https://aidatacenterguide.com/part-4-electrical-and-energy-infrastructure/4-6-lv-distribution-busway-pdus-rpps-and-rack-power' },
  'zayo-route-diversity': { title: "Zayo's Unique Long-Haul Routes, setting the standard for network resilience", publisher: 'Zayo', url: 'https://www.zayo.com/info/zayos-unique-long-haul-routes-setting-the-standard-for-network-resilience/' },

  // cooling and water
  'ashrae-liquid-cooling-classes': { title: "What You Need to Know About ASHRAE's Fifth Edition of Thermal Guidelines", publisher: 'Upsite Technologies', url: 'https://www.upsite.com/blog/what-you-need-to-know-about-ashraes-fifth-edition-of-thermal-guidelines/' },
  'introl-wue': { title: 'Water Usage Efficiency: AI Data Center Cooling Without Crisis', publisher: 'Introl', url: 'https://introl.com/blog/water-usage-efficiency-wue-ai-data-center-cooling-guide-2025' },
  'nrel-water-electricity': { title: 'A review of operational water consumption and withdrawal factors for electricity generating technologies', publisher: 'NREL', url: 'https://docs.nrel.gov/docs/fy11osti/50900.pdf' },
  'vertiv-coolchip-cdu': { title: 'Vertiv CoolChip CDU', publisher: 'Vertiv', url: 'https://www.vertiv.com/en-us/products-catalog/thermal-management/high-density-solutions/vertiv-coolchip-cdu/' },
  'motivair-cdu-brochure': { title: 'CDU 2025 product brochure', publisher: 'Motivair (Schneider Electric)', url: 'https://www.motivaircorp.com/uploads/files/brochures/CDU%202025%20Motivair%20by%20SE_Updated_9_26_25.pdf' },
  'fortum-finland-heat': { title: 'Fortum has started heat production at two large data centre sites in Finland', publisher: 'Fortum', url: 'https://www.fortum.com/en/media/2026/05/fortum-has-started-heat-production-two-large-data-centre-sites-finland' },
  'munters-odense': { title: 'Harnessing heat from Odense data center for reuse in district heating', publisher: 'Munters', url: 'https://www.munters.com/en-us/knowledge-bank/case-studies/casestudy-13666/' },
  'stockholm-data-parks': { title: 'Stockholm Data Parks', publisher: 'Stockholm Exergi / City of Stockholm', url: 'https://stockholmdataparks.com/' },
  'microsoft-zero-water': { title: 'Sustainable by design: next-generation datacenters consume zero water for cooling', publisher: 'Microsoft', url: 'https://www.microsoft.com/en-us/microsoft-cloud/blog/2024/12/09/sustainable-by-design-next-generation-datacenters-consume-zero-water-for-cooling/' },
  'alliance-chemical-gpu-thermal': { title: 'GPU Thermal Density & Coolant Flow Specs: B200, GB200, MI300', publisher: 'Alliance Chemical', url: 'https://alliancechemical.com/blogs/articles/gpu-thermal-density-b200-gb200-coolant-flow-specs' },

  // UPS, PUE
  'eaton-9395xr-ups': { title: '9395XR UPS', publisher: 'Eaton', url: 'https://www.eaton.com/us/en-us/catalog/backup-power-ups-surge-it-power-distribution/eaton-9395xr-ups.html' },
  'google-pue': { title: 'Efficiency — Google Data Centers', publisher: 'Google', url: 'https://datacenters.google/efficiency/' },

  // GB200 / GB300 / 800 V DC rack platform
  'nvidia-gb200-nvl72': { title: 'GB200 NVL72', publisher: 'NVIDIA', url: 'https://www.nvidia.com/en-us/data-center/gb200-nvl72/' },
  'nvidia-gb200-ocp': { title: 'NVIDIA Contributes GB200 NVL72 Designs to Open Compute Project', publisher: 'NVIDIA', url: 'https://developer.nvidia.com/blog/nvidia-contributes-nvidia-gb200-nvl72-designs-to-open-compute-project/' },
  'nvidia-gb300-power': { title: 'How New GB300 NVL72 Features Provide Steady Power for AI', publisher: 'NVIDIA', url: 'https://developer.nvidia.com/blog/how-new-gb300-nvl72-features-provide-steady-power-for-ai/' },
  'nvidia-gb300-nvl72': { title: 'GB300 NVL72', publisher: 'NVIDIA', url: 'https://www.nvidia.com/en-us/data-center/gb300-nvl72/' },
  'nvidia-800v-hvdc': { title: 'NVIDIA 800 V HVDC Architecture Will Power the Next Generation of AI Factories', publisher: 'NVIDIA', url: 'https://developer.nvidia.com/blog/nvidia-800-v-hvdc-architecture-will-power-the-next-generation-of-ai-factories/' },
  'hpe-gb200-quickspecs': { title: 'NVIDIA GB200 NVL72 by HPE, QuickSpecs', publisher: 'HPE', url: 'https://www.hpe.com/us/en/collaterals/collateral.a50009224enw.html' },
  'navitas-800vdc': { title: "Navitas Supports 800 VDC Power Architecture for NVIDIA's Next-Generation AI Factory Computing Platforms", publisher: 'Navitas Semiconductor', url: 'https://navitassemi.com/navitas-supports-800-vdc-power-architecture-for-nvidias-next-generation-ai-factory-computing-platforms/' },
  'liteon-gb200-power-system': { title: 'NVIDIA GB200 Blackwell power system', publisher: 'LITE-ON', url: 'https://www.liteon.com/en/news/press-center/content/nvidia-gb200-blackwell-power-system' },
  'nvidia-nvl72-reference-arch': { title: 'NVL72 AI Factory reference architecture, System Hardware & Components', publisher: 'NVIDIA', url: 'https://docs.nvidia.com/enterprise-reference-architectures/nvl72-ai-factory/latest/components.html' },
  'nvidia-dgx-gb200-hardware': { title: 'DGX GB Rack Scale Systems User Guide, Hardware', publisher: 'NVIDIA', url: 'https://docs.nvidia.com/dgx/dgxgb200-user-guide/hardware.html' },
  'servethehome-dgx-gb200': { title: 'This is the NVIDIA DGX GB200 NVL72', publisher: 'ServeTheHome', url: 'https://www.servethehome.com/this-is-the-nvidia-dgx-gb200-nvl72/' },
  'naddod-gb200-interconnect': { title: 'NVIDIA GB200 Interconnect Architecture Analysis: NVLink, InfiniBand and Future Trends', publisher: 'NADDOD', url: 'https://www.naddod.com/blog/nvidia-gb200-interconnect-architecture-analysis-nvlink-infiniband-and-future-trends' },
  'amphenol-paladin-hd': { title: 'Paladin HD 224Gb/s Backplane Interconnect System', publisher: 'Amphenol', url: 'https://www.amphenol-cs.com/product-series/paladin-hd.html' },
  'semianalysis-nvl72-optics': { title: "NVIDIA's Optical Boogeyman: NVL72, InfiniBand", publisher: 'SemiAnalysis', url: 'https://newsletter.semianalysis.com/p/nvidias-optical-boogeyman-nvl72-infiniband' },
  'semianalysis-gb200-nvl72-specs': { title: 'NVIDIA GB200 NVL72 Specs, Pricing & AI Inference Benchmarks', publisher: 'SemiAnalysis / InferenceX', url: 'https://inferencex.semianalysis.com/chips/gb200-nvl72' },

  // H100 / DGX H100
  'nvidia-h100-datasheet': { title: 'H100 Tensor Core GPU datasheet', publisher: 'NVIDIA', url: 'https://resources.nvidia.com/en-us-gpu-resources/h100-datasheet-24306' },
  'nvidia-dgx-h100': { title: 'DGX H100 product page', publisher: 'NVIDIA', url: 'https://www.nvidia.com/en-eu/data-center/dgx-h100/' },
  'fs-com-dgx-h100': { title: 'Introduction to NVIDIA DGX H100', publisher: 'FS.com', url: 'https://www.fs.com/blog/introduction-to-nvidia-dgx-h100-3856.html' },

  // networking, optics, fiber
  'nvidia-xdr-switch-specs': { title: 'Quantum-X800 XDR switch systems, specifications', publisher: 'NVIDIA', url: 'https://networking-docs.nvidia.com/xdrswitcheshw/specifications' },
  'nvidia-sn5000-specs': { title: 'SN5000 switch systems, specifications', publisher: 'NVIDIA', url: 'https://networking-docs.nvidia.com/sn5000hw/specifications' },
  'nvidia-800g-dr8-datasheet': { title: '800Gb/s Twin-Port OSFP 2x400Gb/s Single-Mode DR8 datasheet', publisher: 'NVIDIA', url: 'https://docs.nvidia.com/nvidia-mms4x00-nm-800gbps-twin-port-osfp-2x400gb-s-single-mode-dr8-500m-12-07-2023.pdf' },
  'nvidia-connectx8-datasheet': { title: 'ConnectX-8 SuperNIC datasheet', publisher: 'NVIDIA', url: 'https://resources.nvidia.com/en-us-accelerated-networking-resource-library/connectx-datasheet-c' },
  'nvidia-spectrum-x-cpo': { title: 'NVIDIA Spectrum-X co-packaged optics networking switches for AI factories', publisher: 'NVIDIA', url: 'https://nvidianews.nvidia.com/news/nvidia-spectrum-x-co-packaged-optics-networking-switches-ai-factories' },
  'broadcom-davisson-cpo': { title: 'Broadcom Davisson co-packaged optics announcement', publisher: 'Broadcom', url: 'https://www.broadcom.com/company/news/product-releases/63626' },
  'nvidia-spectrum-xgs': { title: 'NVIDIA Introduces Spectrum-XGS Ethernet to Connect Distributed Data Centers', publisher: 'NVIDIA', url: 'https://nvidianews.nvidia.com/news/nvidia-introduces-spectrum-xgs-ethernet-to-connect-distributed-data-centers-into-giga-scale-ai-super-factories' },
  'microsoft-ai-wan': { title: 'From Wisconsin to Atlanta: Microsoft connects datacenters to build its first AI superfactory', publisher: 'Microsoft', url: 'https://news.microsoft.com/source/features/ai/from-wisconsin-to-atlanta-microsoft-connects-datacenters-to-build-its-first-ai-superfactory/' },
  'datacenterfrontier-fairwater': { title: "Microsoft's Fairwater Atlanta and the Rise of the Distributed AI Supercomputer", publisher: 'Data Center Frontier', url: 'https://www.datacenterfrontier.com/machine-learning/article/55330039/microsofts-fairwater-atlanta-and-the-rise-of-the-distributed-ai-supercomputer' },
  'google-cloud-networking-ai': { title: 'Data center and global networks built for the AI era', publisher: 'Google Cloud', url: 'https://cloud.google.com/blog/products/networking/data-center-and-global-networks-built-for-ai-era' },
  'deepmind-decoupled-diloco': { title: 'Decoupled DiLoCo', publisher: 'Google DeepMind', url: 'https://deepmind.google/blog/decoupled-diloco/' },
  'ciena-wavelogic6': { title: 'Ciena Unveils WaveLogic 6', publisher: 'Ciena', url: 'https://www.ciena.com/about/newsroom/press-releases/ciena-unveils-wavelogic-6' },
  'corning-edge8': { title: 'EDGE8 Housings', publisher: 'Corning', url: 'https://ecatalog.corning.com/optical-communications/US/en/Fiber-Optic-Hardware/Housings/EDGE8%C2%AE-Housings/p/EDGE8-01U-SP' },
  'coherent-full-cband-pols': { title: 'ECOC: Coherent Extends Pluggable Line System Across Full C-Band', publisher: 'Converge Digest', url: 'https://convergedigest.com/coherent-full-c-band-pols-25-6tbps-ai-dci/' },
  'cisco-8800-routers': { title: '8800 Series Modular Routers data sheet', publisher: 'Cisco', url: 'https://www.cisco.com/c/en/us/products/collateral/routers/8000-series-routers/8800-series-modular-routers-ds.html' },
  'microsoft-hollow-core-fiber': { title: 'Microsoft Scales Up Hollow Core Fiber Production', publisher: 'Fiber Broadband Association', url: 'https://fiberbroadband.org/2026/04/02/microsoft-scales-up-hollow-core-fiber-production/' },
  'prysmian-flexribbon': { title: 'FlexRibbon whitepaper', publisher: 'Prysmian', url: 'https://www.prysmian.com/sites/default/files/business_markets/markets/downloads/datasheets/FlexRibbon-Whitepaper.pdf' },
  'google-ironwood-tpu': { title: 'Ironwood: the first Google TPU for the age of inference', publisher: 'Google Cloud', url: 'https://blog.google/products/google-cloud/ironwood-google-tpu-things-to-know/' },

  // board, chip, power delivery
  'semianalysis-blackwell-power-delivery': { title: 'Energizing AI: Power Delivery Competition Heats Up', publisher: 'SemiAnalysis', url: 'https://newsletter.semianalysis.com/p/energizing-ai-power-delivery-competition' },
  'arxiv-gpu-power-visibility': { title: 'Methodology for Fine-Grain GPU Power Visibility and Insights', publisher: 'arXiv', url: 'https://arxiv.org/html/2412.12426v1' },
  'nvidia-blackwell-ultra-blog': { title: 'Inside NVIDIA Blackwell Ultra: The Chip Powering the AI Factory Era', publisher: 'NVIDIA', url: 'https://developer.nvidia.com/blog/inside-nvidia-blackwell-ultra-the-chip-powering-the-ai-factory-era' },
  'wccftech-nv-hbi': { title: 'NVIDIA Deep-Dives Into Blackwell Infrastructure: NV-HBI Used to Fuse Two AI GPUs Together', publisher: 'WCCFTech', url: 'https://wccftech.com/nvidia-blackwell-ai-deep-dive-nv-hbi-fuse-two-ai-gpus-together-5th-gen-tensor-cores-5th-gen-nvlink-spectrum-x/' },
  'micron-hbm3e-brief': { title: 'HBM3E product brief', publisher: 'Micron', url: 'https://assets.micron.com/adobe/assets/urn:aaid:aem:b710d8f2-7f66-44c1-a234-456e2b986347/original/as/hbm3e-product-brief.pdf' },

  // tokens, training, carbon, models
  'samsi-words-to-watts': { title: 'From Words to Watts: Benchmarking the Energy Costs of Large Language Model Inference', publisher: 'Samsi et al., arXiv', url: 'https://arxiv.org/pdf/2310.03003' },
  'semianalysis-inferencemax': { title: 'InferenceMAX: Open Source Inference Benchmarking', publisher: 'SemiAnalysis', url: 'https://newsletter.semianalysis.com/p/inferencemax-open-source-inference' },
  'google-inference-impact': { title: 'Measuring the environmental impact of AI inference', publisher: 'Google Cloud', url: 'https://cloud.google.com/blog/products/infrastructure/measuring-the-environmental-impact-of-ai-inference/' },
  'google-inference-impact-paper': { title: 'Measuring the environmental impact of delivering AI at Google scale', publisher: 'Google, arXiv', url: 'https://arxiv.org/abs/2508.15734' },
  'meta-llama31-model-card': { title: 'Llama 3.1 model card', publisher: 'Meta', url: 'https://github.com/meta-llama/llama-models/blob/main/models/llama3_1/MODEL_CARD.md' },
  'meta-llama3-herd-parallelism': { title: 'The Llama 3 Herd of Models', publisher: 'Meta AI, arXiv', url: 'https://arxiv.org/pdf/2407.21783' },
  'deepseek-v3-technical-report': { title: 'DeepSeek-V3 Technical Report', publisher: 'DeepSeek-AI, arXiv', url: 'https://arxiv.org/pdf/2412.19437' },
  'nvidia-gb200-dynamo-moe': { title: 'How NVIDIA GB200 NVL72 and NVIDIA Dynamo Boost Inference Performance for MoE Models', publisher: 'NVIDIA', url: 'https://developer.nvidia.com/blog/how-nvidia-gb200-nvl72-and-nvidia-dynamo-boost-inference-performance-for-moe-models' },
  'epoch-chatgpt-energy': { title: 'How much energy does ChatGPT use?', publisher: 'Epoch AI', url: 'https://epoch.ai/gradient-updates/how-much-energy-does-chatgpt-use' },
  'nvidia-hgx-h100-pcf': { title: 'HGX H100 Product Carbon Footprint summary', publisher: 'NVIDIA', url: 'https://images.nvidia.com/aem-dam/Solutions/documents/HGX-H100-PCF-Summary.pdf' },
  // real sites and state carbon (research/scenario-sources.md, sections E and F)
  'dcd-fairwater-atlanta': { title: 'Microsoft launches Atlanta Fairwater AI data center: two stories, no UPS or gen-sets', publisher: 'Data Center Dynamics', url: 'https://www.datacenterdynamics.com/en/news/microsoft-launches-atlanta-fairwater-data-center-two-stories-no-ups-or-gen-sets/' },
  'microsoft-infinite-scale': { title: 'Infinite scale: The architecture behind the Azure AI superfactory', publisher: 'Microsoft', url: 'https://blogs.microsoft.com/blog/2025/11/12/infinite-scale-the-architecture-behind-the-azure-ai-superfactory/' },
  'dcd-fairwater-wisconsin': { title: 'Microsoft increases Wisconsin data center investment to $7.3bn', publisher: 'Data Center Dynamics', url: 'https://www.datacenterdynamics.com/en/news/microsoft-increases-wisconsin-data-center-investment-to-73bn-says-fairwater-site-will-be-worlds-most-powerful-data-center/' },
  'techtimes-fairwater-wisconsin': { title: 'Microsoft Opens Fairwater: Wisconsin AI Campus Runs as One Supercomputer via 800G Ethernet', publisher: 'TechTimes', url: 'https://www.techtimes.com/articles/319205/20260627/microsoft-opens-fairwater-wisconsin-ai-campus-runs-one-supercomputer-via-800g-ethernet.htm' },
  'meta-richland-parish': { title: 'The largest Meta data center yet brings big impact to Louisiana', publisher: 'Meta', url: 'https://datacenters.atmeta.com/richland-parish-data-center/' },
  'cnbc-meta-louisiana': { title: "Meta's Louisiana data center investment to reach $50 billion", publisher: 'CNBC', url: 'https://www.cnbc.com/2026/07/13/meta-louisiana-data-center-investment-reaches-50-billion-amid-ai-push.html' },
  'led-meta-louisiana': { title: 'Meta Commits More Than $50 Billion for North Louisiana Project', publisher: 'Louisiana Economic Development', url: 'https://www.opportunitylouisiana.gov/news/meta-commits-more-than-50-billion-for-north-louisiana-project-becoming-one-of-the-largest-data-centers-in-history' },
  'wikipedia-colossus': { title: 'Colossus (data center)', publisher: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Colossus_(data_center)' },
  'tomshardware-colossus': { title: "Musk's Colossus is fully operational with 200,000 GPUs", publisher: "Tom's Hardware", url: 'https://www.tomshardware.com/tech-industry/artificial-intelligence/musks-colossus-is-fully-operational-with-200-000-gpus-backed-by-tesla-batteries-phase-2-to-consume-300-mw-enough-to-power-300-000-homes' },
  'eia-state-texas': { title: 'Texas Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/texas/' },
  'eia-state-tennessee': { title: 'Tennessee Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/tennessee/' },
  'eia-state-georgia': { title: 'Georgia Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/georgia/' },
  'eia-state-wisconsin': { title: 'Wisconsin Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/wisconsin/' },
  'eia-state-louisiana': { title: 'Louisiana Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/louisiana/' },
  'eia-state-virginia': { title: 'Virginia Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/virginia/' },
  'eia-state-oregon': { title: 'Oregon Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/oregon/' },
  'eia-state-washington': { title: 'Washington Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/washington/' },
  'eia-state-arizona': { title: 'Arizona Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/arizona/' },
  'eia-state-ohio': { title: 'Ohio Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/ohio/' },
  'eia-state-iowa': { title: 'Iowa Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/iowa/' },
  'eia-state-newyork': { title: 'New York Electricity Profile 2024', publisher: 'U.S. Energy Information Administration', url: 'https://www.eia.gov/electricity/state/newyork/' },

  // links: copper and optics — the media ladder, the copper wall, cutaway optics (research/copper-optics-sources.md)
  'ieee-25gbe-wiki': { title: '25 Gigabit Ethernet', publisher: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/25_Gigabit_Ethernet' },
  'ieee-100gbe-wiki': { title: '100 Gigabit Ethernet', publisher: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/100_Gigabit_Ethernet' },
  'ieee-8023dj-electrical-adhoc': { title: 'IEEE 802.3dj electrical ad hoc, copper objectives (Ran, Cisco, Apr 2023)', publisher: 'IEEE 802.3', url: 'https://www.ieee802.org/3/dj/public/adhoc/electrical/23_0420/ran_3dj_elec_02_230420.pdf' },
  'ethernet-alliance-400g-lane': { title: 'Defining the Path to 400 Gbps-per-Lane Ethernet Signaling', publisher: 'Ethernet Alliance', url: 'https://ethernetalliance.org/blog/2026/06/16/defining-the-path-to-400-gbps-per-lane-ethernet-signaling/' },
  'photonics-explained-copper-wall': { title: 'Photonics Explained: Copper vs. Photonics', publisher: 'Photonics Explained (Substack)', url: 'https://tacticzhazel.substack.com/p/photonics-explained-copper-vs-photonics' },
  'link-pp-8023dj-glossary': { title: 'IEEE 802.3dj glossary', publisher: 'link-pp.com', url: 'https://www.link-pp.com/glossary/ieee-802-3dj.html' },
  'photoncap-copper-wall': { title: 'The Copper Wall: Age of Light', publisher: 'photoncap.net', url: 'https://photoncap.net/p/copper-wall-age-of-light-dissecting' },
  'wingvc-marvell-copper-wall': { title: 'Light, Radio, and the Race to Replace Copper Interconnects in the AI Era', publisher: 'Wing VC', url: 'https://www.wing.vc/content/light-radio-and-the-race-to-replace-copper-interconnects-in-the-ai-era' },
  'semiengineering-copper-grip-slipping': { title: "Copper's Grip on AI Scaling Is Starting to Slip", publisher: 'SemiEngineering', url: 'https://semiengineering.com/coppers-grip-on-ai-scaling-is-starting-to-slip/' },
  'nvidia-copper-dac-lacc-overview': { title: 'Copper DAC and LACC Cables Overview', publisher: 'NVIDIA', url: 'https://docs.nvidia.com/networking/display/400g100gpam4ovdev/copper-dac-and-lacc-cables-overview' },
  'nvidia-mca4j80n-datasheet': { title: 'MCA4J80-Nxxx active copper cable datasheet', publisher: 'NVIDIA', url: 'https://networking-docs.nvidia.com/mca4j80nxxx800pub' },
  'viksnewsletter-acc-power': { title: 'How Rack Power Density Is Opening the ACC Market', publisher: "Vik's Newsletter", url: 'https://www.viksnewsletter.com/p/how-rack-power-density-is-opening-acc-market' },
  'nvidia-linkx-interconnect': { title: 'NVIDIA LinkX Interconnects', publisher: 'NVIDIA', url: 'https://www.nvidia.com/en-us/networking/interconnect/' },
  'credo-zeroflap-aec': { title: 'Credo ZeroFlap AEC product page', publisher: 'Credo', url: 'https://credosemi.com/products/zeroflapaec/' },
  'infraeo-9m-aec-release': { title: 'Infraeo Launches 9m 800G OSFP AEC for Next-Gen AI Infrastructure', publisher: 'Infraeo, via PRWeb', url: 'https://www.prweb.com/releases/infraeo-launches-9m-800g-osfp-aec-for-next-gen-ai-infrastructure-302582943.html' },
  'marvell-aec-prnewswire': { title: 'Marvell Expands Interconnect Portfolio with Cloud-Optimized 400G/800G PAM4 DSPs for Active Electrical Cables', publisher: 'Marvell, via PR Newswire', url: 'https://www.prnewswire.com/news-releases/marvell-expands-interconnect-portfolio-with-industrys-1st-cloud-optimized-400g800g-pam4-dsps-for-active-electrical-cables-301493718.html' },
  'lpo-msa-lightwave': { title: 'LPO MSA Releases Linear Pluggable Optical Modules Specification', publisher: 'Lightwave Online', url: 'https://www.lightwaveonline.com/home/article/55278631/lpo-msa-releases-linear-pluggable-optical-modules-specification' },
  'semtech-200g-lpo-power-blog': { title: '200G LPO Power, Reach and Loss: Real Numbers', publisher: 'Semtech', url: 'https://blog.semtech.com/200g-lpo-power-reach-and-loss-real-numbers' },
  'semtech-lpo-ai-basics-blog': { title: 'AI Data Center Basics: What Is Linear Pluggable Optics?', publisher: 'Semtech', url: 'https://blog.semtech.com/ai-data-center-basics-what-is-linear-pluggable-optics-lpo' },
  'ascentoptics-800g-lpo-guide': { title: '800G LPO Guide (2026)', publisher: 'AscentOptics', url: 'https://ascentoptics.com/blog/800g-lpo/' },
  'cisco-400g-qsfpdd-datasheet': { title: '400G QSFP-DD datasheet', publisher: 'Cisco', url: 'https://www.cisco.com/c/en/us/products/collateral/interfaces-modules/transceiver-modules/datasheet-c78-743172.html' },
  'semianalysis-cpo-newsletter': { title: 'Co-Packaged Optics (CPO): The Book on Scaling', publisher: 'SemiAnalysis', url: 'https://newsletter.semianalysis.com/p/co-packaged-optics-cpo-book-scaling' },
  'broadcom-sian3-200g-lane-dsp': { title: 'Broadcom Extends 200G-Lane DSP PHY Leadership for Next-Generation AI Infrastructure', publisher: 'Broadcom, via GlobeNewswire', url: 'https://www.globenewswire.com/news-release/2025/03/25/3048831/19933/en/broadcom-extends-200g-lane-dsp-phy-leadership-for-next-generation-ai-infrastructure.html' },
  'marvell-ara-1-6t-prnewswire': { title: "Marvell Unveils Industry's First 3nm 1.6 Tbps PAM4 Interconnect Platform", publisher: 'Marvell, via PRNewswire', url: 'https://www.prnewswire.com/news-releases/marvell-unveils-industrys-first-3nm-1-6-tbps-pam4-interconnect-platform-to-scale-accelerated-infrastructure-302320829.html' },
  'nextplatform-broadcom-cpo': { title: 'The Third Time Will Be the Charm for Broadcom Switch Co-Packaged Optics', publisher: 'The Next Platform', url: 'https://www.nextplatform.com/2025/10/17/the-third-time-will-be-the-charm-for-broadcom-switch-co-packaged-optics/' },
  'micasnetworks-51-2t-release': { title: 'Micas Networks 51.2T CPO system reaches volume production', publisher: 'Micas Networks', url: 'https://micasnetworks.com/company/news/30202' },
  'storagereview-nvidia-cpo-production': { title: 'NVIDIA Spectrum-X Ethernet Photonics Enters Full Production', publisher: 'StorageReview', url: 'https://www.storagereview.com/news/nvidia-spectrum-x-ethernet-photonics-enters-full-production-with-4x-fewer-lasers-and-a-five-vendor-cpo-supply-chain' },
  'broadcom-davisson-servethehome': { title: 'Broadcom Tomahawk 6 "Davisson" 102.4T Switch with Co-Packaged Optics Shipping', publisher: 'ServeTheHome', url: 'https://www.servethehome.com/broadcom-tomahawk-6-davisson-102-4t-switch-with-co-packaged-optics-shipping/' },
  'lcom-lr4-10km': { title: 'LR4 Optics Solutions: 10km Long-Haul Data Center Links', publisher: 'L-Com', url: 'https://www.l-p.com/blog/use-cases-solutions/lr4-optics-solutions-10km-long-haul-data-center-links.htm' },
  'nvidia-dgx-gb200-user-guide': { title: 'DGX GB200 User Guide, hardware overview', publisher: 'NVIDIA', url: 'https://docs.nvidia.com/dgx/dgxgb200-user-guide/hardware.html' },
  'arxiv-2601-14342': { title: 'Shoreline bandwidth density and interconnect scaling (arXiv 2601.14342, Kohli & Teissier)', publisher: 'arXiv', url: 'https://arxiv.org/abs/2601.14342' },
};

// PART_SOURCES: which sources back the specs on each card. Key = '<layer>:<sceneId>:<partId>',
// layer is 'power' | 'data' | 'heat'. Empty array = the card is estimate-only, no source to cite.
export const PART_SOURCES = {
  // ---- power ----
  'power:across:carbon': ['eia-state-texas', 'eia-state-tennessee', 'eia-state-georgia', 'eia-state-wisconsin', 'eia-state-louisiana', 'eia-state-washington', 'eia-co2-per-kwh'],
  'power:across:site-abilene': ['epoch-dc-abilene', 'epoch-stargate-abilene'],
  'power:across:site-colossus1': ['compute-atlas-colossus', 'epoch-dc-colossus2', 'epoch-largest-dc', 'wikipedia-colossus', 'tomshardware-colossus', 'semianalysis-xai-colossus2'],
  'power:across:site-fairwater-atl': ['epoch-dc-fairwater-atl', 'microsoft-infinite-scale', 'dcd-fairwater-atlanta', 'datacenterfrontier-fairwater'],
  'power:across:site-fairwater-wi': ['epoch-dc-fairwater-wi', 'dcd-fairwater-wisconsin', 'techtimes-fairwater-wisconsin'],
  'power:across:site-rainier': ['epoch-dc-new-carlisle', 'eia-state-indiana', 'measuredai-new-carlisle', 'compute-atlas-rainier', 'blackridge-rainier'],
  'power:across:site-prometheus': ['epoch-dc-prometheus', 'epoch-satellite-prometheus', 'mlq-meta-gas-tents', 'measuredai-prometheus-primer', 'eia-state-ohio', 'techcrunch-meta-tents'],
  'power:across:site-hyperion': ['epoch-dc-hyperion', 'meta-richland-parish', 'cnbc-meta-louisiana', 'led-meta-louisiana'],
  'power:across:grid': ['ieee-spectrum-hyperion', 'epoch-stargate-abilene'],
  'power:across:plants': ['eia-td-losses'],
  'power:across:home': [],

  'power:campus:line': ['eia-td-losses', 'epoch-stargate-abilene'],
  'power:campus:substation': [],
  'power:campus:mpt': ['pa-transformer-345kv', 'transformer-lead-times'],
  'power:campus:ehouse': ['mv-distribution-atk'],
  'power:campus:gensets': ['cummins-dqkan-genset', 'cummins-qsk78', 'cat-c175-16'],
  'power:campus:fuel': ['cummins-dqkan-genset'],
  'power:campus:bess': ['nvidia-bess-blog', 'dcd-xai-colossus-memphis'],
  'power:campus:unitsubs': ['doe-transformer-efficiency'],
  'power:campus:hall': [],
  'power:campus:drycoolers': ['ashrae-liquid-cooling-classes', 'introl-wue', 'evapco-apex', 'bac-data-centers'],
  'power:campus:chillers': ['schneider-uniflair'],
  'power:campus:towers': ['introl-wue', 'nrel-water-electricity'],
  'power:campus:fiber': ['zayo-route-diversity'],

  'power:hall:unitsub': ['doe-transformer-efficiency'],
  'power:hall:swgr': [],
  'power:hall:sst': ['navitas-800vdc', 'nvidia-800v-hvdc', 'delta-ocp-800vdc', 'infineon-solaredge-sst'],
  'power:hall:ups': ['eaton-9395xr-ups'],
  'power:hall:batt': [],
  'power:hall:busway': ['lv-distribution-busway', 'nvidia-800v-hvdc'],
  'power:hall:racks': ['nvidia-gb200-nvl72', 'hpe-gb200-quickspecs', 'nvidia-dgx-h100'],
  'power:hall:containment': [],
  'power:hall:inrow': [],
  'power:hall:cdu': ['vertiv-coolchip-cdu', 'motivair-cdu-brochure'],
  'power:hall:fwater': [],
  'power:hall:fanwall': [],
  'power:hall:network': [],

  'power:rack:feed': [],
  'power:rack:shelves': ['navitas-800vdc', 'nvidia-gb200-ocp', 'liteon-gb200-power-system', 'delta-ocp-800vdc', 'liteon-gtc-2026'],
  'power:rack:busbar': ['nvidia-gb200-ocp', 'nvidia-800v-hvdc'],
  'power:rack:compute': ['nvidia-gb200-nvl72'],
  'power:rack:nvswitch': ['nvidia-nvl72-reference-arch'],
  'power:rack:spine': ['nvidia-gb200-ocp', 'servethehome-dgx-gb200', 'nvidia-dgx-gb200-user-guide', 'viksnewsletter-acc-power', 'arxiv-2601-14342'],
  'power:rack:manifold': [],
  'power:rack:pdu': [],
  'power:rack:servers': ['nvidia-dgx-h100', 'nvidia-h100-datasheet'],
  'power:rack:psus': ['fs-com-dgx-h100'],
  'power:rack:cabling': [],
  'power:rack:mgmt': [],

  'power:tray:clip': [],
  'power:tray:ibc': ['semianalysis-blackwell-power-delivery'],
  'power:tray:vrm': ['semianalysis-blackwell-power-delivery'],
  'power:tray:gpu': ['nvidia-gb200-nvl72', 'nvidia-gb300-nvl72', 'nvidia-h100-datasheet'],
  'power:tray:grace': ['nvidia-gb200-nvl72'],
  'power:tray:lpddr': ['nvidia-gb200-nvl72'],
  'power:tray:coldplates': [],
  'power:tray:nic': ['nvidia-connectx8-datasheet', 'nvidia-gb300-nvl72', 'nvidia-dpu-supernic', 'nvidia-bluefield-datasheet'],
  'power:tray:nvconn': ['nvidia-gb200-nvl72'],
  'power:tray:psu': ['fs-com-dgx-h100'],
  'power:tray:cpu': [],
  'power:tray:heatsinks': [],
  'power:tray:nvswitch': ['nvidia-h100-datasheet'],

  'power:chip:balls': ['semianalysis-blackwell-power-delivery'],
  'power:chip:interposer': ['nvidia-blackwell-ultra-blog', 'wccftech-nv-hbi'],
  'power:chip:dies': ['nvidia-blackwell-ultra-blog', 'wccftech-nv-hbi'],
  'power:chip:hbm': ['micron-hbm3e-brief', 'arxiv-gpu-power-visibility', 'skhynix-hbm4', 'micron-hbm4', 'samsung-hbm4'],
  'power:chip:tokens': ['google-inference-impact', 'samsi-words-to-watts'],

  // ---- data ----
  'data:across:dci': ['ciena-wavelogic6', 'marvell-colorz-800', 'ciena-wavelogic6-nano'],
  'data:across:ila': [],
  'data:across:route': ['microsoft-hollow-core-fiber', 'coherent-full-cband-pols'],
  'data:across:remote': ['microsoft-ai-wan', 'nvidia-spectrum-xgs', 'deepmind-decoupled-diloco'],
  'data:across:home': [],

  'data:campus:fiber': ['zayo-route-diversity'],
  'data:campus:dci': ['ciena-wavelogic6'],
  'data:campus:interhall': [],
  'data:campus:ductbank': ['prysmian-flexribbon'],
  'data:campus:hall': [],
  'data:campus:longhaul': [],

  'data:hall:odf': ['corning-edge8'],
  'data:hall:crosshall': [],
  'data:hall:pp': ['meta-llama3-herd-parallelism'],
  'data:hall:dp': ['meta-llama3-herd-parallelism', 'deepseek-v3-technical-report'],
  'data:hall:uplinks': [],
  'data:hall:leaf': ['nvidia-sn5000-datasheet', 'nvidia-quantum-x800-switches', 'nvidia-rubin-platform'],
  'data:hall:spine': ['nvidia-xdr-switch-specs', 'nvidia-rubin-platform', 'broadcom-tomahawk6', 'marvell-teralynx10'],
  'data:hall:runways': [],
  'data:hall:optics': ['nvidia-800g-dr8-datasheet', 'innolight-1p6t', 'coherent-1p6t-dr8', 'marvell-ara-1p6t-portfolio', 'broadcom-sian3-200g-lane-dsp', 'credo-bluebird-dsp'],
  'data:hall:cpo': ['nvidia-spectrum-x-cpo', 'broadcom-davisson-cpo'],
  'data:hall:racks': ['nvidia-gb200-nvl72'],

  'data:rack:tp': ['meta-llama3-herd-parallelism'],
  'data:rack:nvswitch': ['nvidia-nvl72-reference-arch'],
  'data:rack:spine': ['nvidia-gb200-ocp', 'servethehome-dgx-gb200', 'nvidia-dgx-gb200-user-guide', 'viksnewsletter-acc-power', 'arxiv-2601-14342'],
  'data:rack:optical': ['google-ironwood-tpu'],
  'data:rack:uplinks': ['nvidia-h100-datasheet'],
  'data:rack:compute': [],
  'data:rack:mgmt': [],
  'data:rack:servers': ['nvidia-h100-datasheet'],

  'data:tray:nvconn': ['nvidia-gb200-nvl72'],
  'data:tray:c2c': ['nvidia-gb200-nvl72', 'naddod-gb200-interconnect'],
  'data:tray:cx': ['nvidia-connectx8-datasheet', 'fs-com-dgx-h100'],
  'data:tray:osfp': ['nvidia-800g-dr8-datasheet'],
  'data:tray:dpu': ['nvidia-dgx-gb200-hardware', 'nvidia-bluefield4-datasheet'],
  'data:tray:gpu': [],
  'data:tray:nvswitch': ['nvidia-h100-datasheet'],
  'data:tray:pcie': [],

  'data:chip:hbm': ['micron-hbm3e-brief'],
  'data:chip:hbi': ['wccftech-nv-hbi'],
  'data:chip:nvphy': [],
  'data:chip:cpo': ['nvidia-spectrum-x-cpo'],
  'data:chip:tokens': [],

  // ---- heat ----
  'heat:across:climate': [],
  'heat:across:home': [],

  'heat:campus:drycoolers': ['ashrae-liquid-cooling-classes', 'alliance-chemical-gpu-thermal'],
  'heat:campus:chillers': [],
  'heat:campus:towers': ['introl-wue', 'nrel-water-electricity'],
  'heat:campus:plume': [],
  'heat:campus:reuse': ['fortum-finland-heat', 'munters-odense', 'stockholm-data-parks'],

  'heat:hall:inrow': [],
  'heat:hall:cdu': ['vertiv-coolchip-cdu', 'motivair-cdu-brochure'],
  'heat:hall:fwater': [],
  'heat:hall:hotaisle': [],
  'heat:hall:fanwall': [],
  'heat:hall:riser': [],

  'heat:rack:manifold': ['alliance-chemical-gpu-thermal'],
  'heat:rack:rearair': [],
  'heat:rack:compute': [],
  'heat:rack:front': [],
  'heat:rack:servers': [],

  'heat:tray:coldplates': [],
  'heat:tray:gpuheat': [],
  'heat:tray:fans': [],
  'heat:tray:qd': [],
  'heat:tray:heatsinks': [],

  'heat:chip:junction': [],
  'heat:chip:flux': ['alliance-chemical-gpu-thermal'],
  'heat:chip:tim': [],
  'heat:chip:hbm': ['micron-hbm3e-brief'],

  // ---- links: the media ladder, the copper wall, cutaway optics (3.2 · Links) ----
  'links:dac': ['ieee-25gbe-wiki', 'ieee-100gbe-wiki', 'ieee-8023dj-electrical-adhoc', 'ethernet-alliance-400g-lane', 'photonics-explained-copper-wall', 'link-pp-8023dj-glossary', 'photoncap-copper-wall'],
  'links:acc': ['nvidia-copper-dac-lacc-overview', 'nvidia-mca4j80n-datasheet', 'viksnewsletter-acc-power', 'ieee-8023dj-electrical-adhoc'],
  'links:aec': ['nvidia-linkx-interconnect', 'credo-zeroflap-aec', 'infraeo-9m-aec-release', 'viksnewsletter-acc-power', 'marvell-aec-prnewswire', 'ieee-8023dj-electrical-adhoc', 'marvell-alaska-a-aec', 'credo-hiwire-800g-aec', 'astera-taurus-scm'],
  'links:lpo': ['lpo-msa-lightwave', 'semtech-200g-lpo-power-blog', 'semtech-lpo-ai-basics-blog', 'ascentoptics-800g-lpo-guide'],
  'links:dsp': ['cisco-400g-qsfpdd-datasheet', 'semianalysis-cpo-newsletter', 'broadcom-sian3-200g-lane-dsp', 'marvell-ara-1-6t-prnewswire', 'marvell-ara-1p6t-portfolio', 'credo-bluebird-dsp'],
  'links:cpo': ['nvidia-spectrum-x-cpo', 'broadcom-davisson-cpo', 'nextplatform-broadcom-cpo', 'micasnetworks-51-2t-release', 'storagereview-nvidia-cpo-production', 'broadcom-davisson-servethehome'],
  'links:coherent': ['ciena-wavelogic6', 'lcom-lr4-10km', 'marvell-colorz-800', 'ciena-wavelogic6-nano'],
  'links:copperwall': ['ieee-25gbe-wiki', 'ieee-100gbe-wiki', 'ieee-8023dj-electrical-adhoc', 'ethernet-alliance-400g-lane', 'photonics-explained-copper-wall', 'link-pp-8023dj-glossary', 'photoncap-copper-wall', 'wingvc-marvell-copper-wall', 'semiengineering-copper-grip-slipping'],
  'links:cutaway-dsp': ['cisco-400g-qsfpdd-datasheet', 'semianalysis-cpo-newsletter', 'broadcom-sian3-200g-lane-dsp'],
  'links:cutaway-lpo': ['semtech-200g-lpo-power-blog', 'ascentoptics-800g-lpo-guide'],
  'links:cutaway-cpo': ['nvidia-spectrum-x-cpo', 'broadcom-davisson-cpo', 'broadcom-davisson-servethehome'],
};

// LEDGER_SOURCES: [labelPrefix, sourceIds] pairs, matched with row.label.startsWith(prefix).
export const LEDGER_SOURCES = [
  ['Main power transformers', ['pa-transformer-345kv', 'transformer-lead-times']],
  ['Campus cables & switchgear', []],
  ['Unit substations', ['doe-transformer-efficiency']],
  ['Solid-state transformers', ['navitas-800vdc', 'nvidia-800v-hvdc']],
  ['800 V DC bus & batteries', ['nvidia-800v-hvdc']],
  ['UPS, double conversion', ['eaton-9395xr-ups']],
  ['Busway & whips', ['lv-distribution-busway', 'nvidia-800v-hvdc']],
  ['Cooling:', ['ashrae-liquid-cooling-classes', 'introl-wue']],
  ['Lighting, controls, offices', []],
  ['Scale-out switches', ['nvidia-xdr-switch-specs']],
  ['Optical transceivers', ['nvidia-800g-dr8-datasheet']],
  ['In-rack DC-DC', ['navitas-800vdc']],
  ['Server power supplies', ['fs-com-dgx-h100']],
  ['Rack power shelves', ['liteon-gb200-power-system', 'nvidia-gb200-ocp']],
  ['Server power cabling', []],
  ['Busbar', ['nvidia-gb200-ocp']],
  ['NVSwitch chips', ['nvidia-h100-datasheet']],
  ['NVLink switch trays', ['nvidia-nvl72-reference-arch']],
  ['x86 CPUs', []],
  ['Grace CPUs', ['nvidia-gb200-nvl72']],
  ['Vera CPUs', []],
  ['NICs & DPUs', ['fs-com-dgx-h100']],
  ['SuperNICs & DPUs', ['nvidia-connectx8-datasheet']],
  ['SSDs, fans, management', []],
  ['Bus converters', ['semianalysis-blackwell-power-delivery']],
  ['Voltage regulators', ['semianalysis-blackwell-power-delivery']],
  ['HBM', ['micron-hbm3e-brief']],
];

// EST_NOTES: one sentence on how an estimate was derived, only where data.js's own formula
// or the research notes actually say so.
export const EST_NOTES = {
  'power:campus:line': 'Per-phase current from campus MW ÷ (√3 × 345 kV × 0.95 assumed power factor).',
  'power:campus:fuel': 'Tanker count from the 48-hour fuel volume ÷ 30,000 L per truckload.',
  'power:hall:unitsub': 'Secondary current from 2.5 MVA ÷ (√3 × 480 V × 0.95 assumed power factor).',
  'power:hall:busway': 'Per-rack current from rack kW ÷ (√3 × 415 V × 0.95 assumed power factor).',
  'power:hall:racks': 'Liquid/air kW split from the rack total × HPE\'s published liquid share for this rack.',
  'power:rack:busbar': 'Busbar current from the rack DC bus power ÷ 50 V.',
  'power:chip:balls': 'Core current from GPU power (minus HBM share) ÷ 0.8 V assumed core voltage.',
  'power:tray:vrm': 'Core current from GPU power (minus HBM share) ÷ 0.8 V assumed core voltage.',
  'heat:chip:flux': 'Average flux from GPU power (minus HBM share) ÷ die area; hot spots run well above this average.',
  'heat:tray:fans': 'Airflow from rack heat, air density and specific heat at a 15 °C rise (Q = ṁ·cp·ΔT).',
};
